### ISSUE TITLE
Videos show up in camera category instead of movies

### ISSUE THREAD

**Issue by sidgames5** [FossifyOrg/Gallery#106]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

CalyxOS 5.3.2 Android 14

### Affected device model

Pixel 4a 5G

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Take a video with the default android camera app
2. Open fossify gallery
3. See bug

### Expected behavior

The video should appear in the movies category

### Actual behavior

The video appears in the camera gategory

**Comment by Aga-C** [comment]
Gallery app doesn't group files by its type. It's grouped by directory where it is located. You have your recorded videos in `Camera` because your Camera app saves them there.
