### ISSUE TITLE
Phone does not ring in Do Not Disturb mode when favorite calls 

### ISSUE THREAD

**Issue by Stitch10925** [FossifyOrg/Gallery#115]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

Phone Dialer 5.18.1

### Affected Android/Custom ROM version

Android 10

### Affected device model

Honor 10

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Add a contact to your favorites
2. Make sure the phone is configured to allow calls from favorites in Do Not Disturb mode
3. Enable Do Not Disturb mode
4. Have the favorite contact call your phone

### Expected behavior

I expect the phone to ring when a favorite calls me when Do Not Disturb is enabled.

### Actual behavior

I can see the incoming call, but the phone does not ring.

**Comment by Aga-C** [comment]
Is this contact stored in Fossify Contacts in `Phone storage (not visible by other apps)`?

**Comment by Aga-C** [comment]
Please move this issue to Fossify Phone repository. It's Gallery.
Also, while raising once again, please answer the question: is this contact stored in Fossify Contacts in `Phone storage (not visible by other apps)`?
