### ISSUE TITLE
Custom Video Playback Speed Control

### ISSUE THREAD

**Issue by Ehab-d** [FossifyOrg/Gallery#116]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

allows users to control the playback speed of videos (e.g., 0.75x, 1x, 1.25x, etc.).

### Why do you want this feature?

Increased accessibility.

### Additional information

Implementation ideas:
- **Granular speed control:** Adjust the speed with a slider or input box, offering increments of 0.1x or 0.25x.
- **Remember last used speed:** Optionally, remember the last chosen speed.
Thank you ♡

**Comment by Gamer750** [comment]
Any update

**Comment by GfEW** [comment]
I'd like to add some emphasis on the ease of access to the new UI element for changing the playback speed. 

Although there are several _functionally_ equivalent design variants, they can be vastly different _ergonomically_. E. g., a **vertical two finger slide** on the player screen allows much quicker adjustments to playback speed when needed and are, for most users, easier to access, than a playback speed setting that is buried in a menu.
To get some practical idea of the former, see e. g. MXPlayer. For the latter, see e. g. VLC for Android, especially when current speed (before the change) is 1.0, where speed changes are available only after multiple, consequtive, well aimed taps.

**Comment by Gamer750** [comment]
Is anyone working on this feature

**Comment by Natolu24** [comment]
Me and my fellow are still working on it, hoping to get it done within the few weeks to come !

**Comment by Gamer750** [comment]
> Me and my fellow are still working on it, hoping to get it done within the few weeks to come !

Will there will be default playback speed because I always watch in 2x speed so it will be annoying to go and change it to 2x speed

**Comment by Natolu24** [comment]
Ohh yes that sounds like something doable, we'll add it

**Comment by Gamer750** [comment]
> Ohh yes that sounds like something doable, we'll add it

Thanks
