### ISSUE TITLE
[ Bug ] "Password protect the whole application" option is not respected when photos/videos are opened by another app.

### ISSUE THREAD

**Issue by onegladius** [FossifyOrg/Gallery#126]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [x] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 10

### Affected device model

Motorola moto e7 Power

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open the Fossify Gallery app.
2. Click on the 3 dots on the top right.
3. Click on "Settings".
4. Scroll down to "SECURITY" and enable "Password protect the whole application".
5. Exit the gallery app.
6. Open a photo viewing app that does NOT have a built in gallery ( e.g. Simple Camera, Fossify File Manager )
7. Click on a picture

### Expected behavior

It should ask for the PIN code in order for the photos/videos taken to be seen, and if not entered correctly further access should not be allowed.

### Actual behavior

It directly opens the folder's contents, and the "ENTER PIN" overlay is only shown when trying to delete a photo/video ( if "Password protect file deletion and moving" is enabled ).

### Screenshots/Screen recordings

Here is a video where I show the bug using the Camera app. It also happens when using the file manager, or basically any app that does not have a built in gallery and depends on the default gallery app.

https://github.com/FossifyOrg/Camera/assets/158749828/7057361c-2827-4e15-b142-1df85a028805

### Additional information

• If the "Password protect file deletion and moving" option is enabled, it will be respected.

• I have tested with both Gallery apps ( Fossify and SMT latest release ) and both have the same issue.

**Comment by the-netspider** [comment]
Yes Its a must needed feature... At least while opening via cross app, opening settings menu must be restricted.!!
Thanks

**Comment by naveensingh** [comment]
Should be fixed in the next update. The unlock UI will now be displayed in full screen:

<img src="https://github.com/user-attachments/assets/88f84bf7-0873-4537-bc1c-c660a3dfc966" width=200> <img src="https://github.com/user-attachments/assets/f1ebf103-ac95-49f2-b665-751ac6302530" width=200>

**Notes:**

- App will be locked instantly on back press.

- App will be locked after 30 seconds when closed using any other gesture or method.
