### ISSUE TITLE
Allow disable fade-in of thumbnails when scrolling

### ISSUE THREAD

**Issue by CurbedLarry** [FossifyOrg/Gallery#136]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Allow disable fade-in of thumbnails to increase scrolling speed, reduce CPU/GPU use

### Why do you want this feature?

Main issue stopping me moving on from QuickPic is sluggish scrolling of thumbnails, especially on older/slower devices.  This appears to be because thumbnails fade into view from black.  I assume this was an aesthetic choice and not for some other technical reason?  On faster/recent devices the fade-in effect isn't that noticeable so I think it adds little value.

My hope is the effect could be made optional in the settings?

**Comment by gmasil** [comment]
Related: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2796
My impression is that loading is actually slow, it is more apparent without the fade-in.

**Comment by CurbedLarry** [comment]
@gmasil Thanks for linking to the previous request.

Have noticed QuickPic is creating smaller thumbnails which surely helps.  For the same ~3,000 images QuickPic has a cache of 93MB and Gallery 229MB.  You really have to look closely at thumbnails with text to notice the difference on screen.

Cache size has been raised before I don't think anyone suggested a thumbnail quality setting or just reducing size/quality to benefit performance?

QuickPic
![QuickPic-Thumbnail](https://github.com/FossifyOrg/Gallery/assets/51749382/5f9b8793-d4a4-4aad-8963-2bacc9617a58)
Gallery
![Fossify-Gallery-Thumbnail](https://github.com/FossifyOrg/Gallery/assets/51749382/5377bf47-b0d6-4553-b2d6-e6311ddbdc69)

**Comment by gmasil** [comment]
Hi, that's a good point. I turned down the thumbnail resolution, but it didn't seem to have an impact.
I started a branch here to investigate: https://github.com/gmasil/Fossify-Gallery/tree/investigate-slow-image-scrolling
There is some lazy loading mechanism that I turned off and increased the prefetching of images during scrolling.
Sadly this is running on the UI thread and thus introduces a stuttering UI during the eager thumbnail loading. Once all images are loaded the scrolling is very fast and smooth.

**Comment by CurbedLarry** [comment]
I can't help on the coding front but happy to test APKs.

I've tested a couple of other galleries including Aves (https://github.com/deckerst/aves/).  The UI is horrific and it's very slow creating thumbnails but after that it has fast pop-up of thumbnails when scrolling.  It's hard to make the screen go entirely black, even when throwing the scroll bar up/down.

Can anything be learned from their code?

**Comment by naveensingh** [comment]
I have reduced the fade-in duration from 300ms to 150ms in [version 1.1.3](https://github.com/FossifyOrg/Gallery/releases/tag/1.1.3) but as @gmasil pointed out above, it is the image loader that needs to be optimized. Running the code on the main thread isn't helping either.

**Comment by BluePixel4k** [comment]
@naveensingh thank you for the improvement!
But could you please add a setting to disable the fade-in duration completely? Thx :)

**Comment by naveensingh** [comment]
> sluggish scrolling of thumbnails

This should be fixed in the next update. There was a (unnecessary) lazy loading mechanism that delayed loading by 100 milliseconds. 

I have also _conditionally_ disabled fade-in animation when loading from cache because it usually is instantaneous on most devices.

**Comment by CurbedLarry** [comment]
Just tested v1.2.1 and loading/scrolling is so fast now!  As fast as any gallery I've tested, great work!
