### ISSUE TITLE
No shortcuts under image on Lenevo tablet

### ISSUE THREAD

**Issue by lianergoist** [FossifyOrg/Gallery#141]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 13

### Affected device model

Lenovo TB128XU

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. open Gallery
2. open an image

### Expected behavior

Under the image I expect to see 4 shortcuts to mark as favorite, edit, share and recycle bin.

### Actual behavior

The are no shortcuts

Everything works fine on my Motorola phone with android 9 with the same version of Gallery.

### This is how it looks on my tablet - no shortcuts
<img alt="Screenshot_20240221-091950" src="https://github.com/FossifyOrg/Gallery/assets/6023573/8fc99346-debb-468d-ab91-127aa9bb0b30" width=240 />

### -- and this is how it looks on my phone - note the shortcuts under the image
<img alt="Screenshot_20240221-092439" src="https://github.com/FossifyOrg/Gallery/assets/6023573/ea58c08c-e249-4886-babd-94c015b5d0a4" width=198 />

### Additional information

This bug started back in SMT-days, after my tablet was upgraded from android 11 to 13. In filed a bug report then, but it was never fixed.

**Comment by inson1** [comment]
https://github.com/SimpleMobileTools/Simple-Gallery/issues/3045

**Comment by lianergoist** [comment]
Lenovo has just released another update, and now everything works as expected. I am closing this issue.
