### ISSUE TITLE
Improve scroll experience.

### ISSUE THREAD

**Issue by UniverseCodex01** [FossifyOrg/Gallery#147]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add an option to Save loaded Thumbnails on cache or data to avoid thumbnail reload on every scroll.

### Why do you want this feature?

This function will increase app storage consumption but will improve performance and UI experience for low end devices and can avoids thumbnail load delay for higher pictures.

### Additional information

Great gallery 😄

**Comment by furdiburd** [comment]
Is it supposed to be cached...

**Comment by UniverseCodex01** [comment]
> Is it supposed to be cached...

On my case, thumbnails are loading on scroll and every time that I close and open the app, loads start again.

**Comment by furdiburd** [comment]
https://github.com/FossifyOrg/Gallery/assets/93724729/0e5c42cb-0930-411e-bc56-2e496ee94a79

worse than this?

**Comment by UniverseCodex01** [comment]
> 
> https://github.com/FossifyOrg/Gallery/assets/93724729/0e5c42cb-0930-411e-bc56-2e496ee94a79
> 
> worse than this?
> 
> 

I'm on low end device, wait now I don't have battery, letter I will share two videos, expected behaviour and actual behaviour to show my idea/case

**Comment by Aga-C** [comment]
Thumbnails are currently cached. The slow scrolling experience is probably caused by the fade-in animation, and there is already a request for that: https://github.com/FossifyOrg/Gallery/issues/136.
