### ISSUE TITLE
some thumbnails wont render

### ISSUE THREAD

**Issue by Meteor0id** [FossifyOrg/Gallery#148]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

android 10

### Affected device model

Motorola moto g7 plus (nearly stock android)

### How did you install the app?

None

### Steps to reproduce the bug

Hi, I noticed some previews aren't rendering for all types of media (videos, gifs, movie). Clearing cache made no difference. These media can still be viewed properly by tapping and opening single view mode.
I have attached one of the images for which the app fails to show a preview in folder view.

Hope this helps.

### Expected behavior

Thumbnails render while scrolling the gallery

### Actual behavior

Thumbnails never shows up

### Screenshots/Screen recordings

<img alt="Screenshot_20240227-162354" src="https://github.com/FossifyOrg/Gallery/assets/34976212/2d1eee13-5da8-490d-a543-2f17a9e38e58" width=190 />

Here is the file itself

<img alt="RDT_20240217_1337493113863773608935546" src="https://github.com/FossifyOrg/Gallery/assets/34976212/eccb25bf-76f3-414f-b36b-dc0df4e46739" width=225 />

And zipped to preserve properties
[RDT_20240217_1337493113863773608935546.zip](https://github.com/FossifyOrg/Gallery/files/14421881/RDT_20240217_1337493113863773608935546.zip)

**Comment by Aga-C** [comment]
1. Fill the template properly, especially fields about the device.
2. 6.28.1 is not the latest version of the app.
3. File link doesn't work.

**Comment by Meteor0id** [comment]
@Aga-C updated, moto g7. Can't see an obvious reason why my device is affected anything I could check?

**Comment by Aga-C** [comment]
@naveensingh Do you have any idea what more information we may need?

**Comment by Meteor0id** [comment]
Settings 
![Screenshot_20240227-165520](https://github.com/FossifyOrg/Gallery/assets/34976212/4fedbcad-6b6e-4aa8-b3d0-1a3f8324409e)

Color sceme looks like old app but was imported

**Comment by inson1** [comment]
its jpg, not crazy big, resolution is little bit bigger, but still in the norm 2k/4k

**Comment by naveensingh** [comment]
> @naveensingh Do you have any idea what more information we may need?

Maybe. @Meteor0id are you familiar with Android Studio or `adb logcat`? Can you provide us with one? Glide often dumps useful info into the logs.

I have one Motorola phone with similar specs, I'll try to reproduce this. I think I might have seen this bug before on an emulator.

**Comment by Aga-C** [comment]
@Meteor0id Do thumbnails work correctly when you turn off `Animate GIFs at thumbnails`?

**Comment by naveensingh** [comment]
Possibly related: https://www.reddit.com/r/Fossify/comments/1b43ifl/gallery_many_gif_thumbnails_missing/

I was gonna create a separate issue but this one might suffice.

**Comment by Meteor0id** [comment]
@Aga-C yes turning that off kakes them appear. You are onto something

**Comment by Aga-C** [comment]
It seems to be only related to this setting, not to the device as I previously thought. Also, thumbnails for AVIF files doesn't work with this option turned on.

In code, I see that problem is with the line `options.dontAnimate()` in `Context.loadImageBase`. For some reason, it breaks both AVIF files and this JPEG.

**Comment by naveensingh** [comment]
I can also reproduce this now. Both with AVIF and the JPG provided above. I'll investigate this later today. 

Thanks, Agni!

**Comment by Aga-C** [comment]
I've found out what's wrong with JPEG posted here. In fact, the file doesn't contain JPEG data but PNG data. For some reason, `dontAnimate` doesn't handle the case of wrong file extension.

**Comment by naveensingh** [comment]
![image](https://github.com/FossifyOrg/Gallery/assets/36371707/4ab66ad3-97d1-46fe-98a1-88224fbfdbff)
Hmmm.

**Comment by naveensingh** [comment]
Should be fixed in https://github.com/FossifyOrg/Gallery/releases/tag/1.1.3
