### ISSUE TITLE
Edit, "Keep old change date" not working

### ISSUE THREAD

**Issue by firefoxlover** [FossifyOrg/Gallery#154]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

GrapheneOS Android 14

### Affected device model

Pixel 6a

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

In settings, enable "keep old date on file operations"

Change a file, save it under the same name (remove the _1, regular way expected when editing a file), check its metadata

### Expected behavior

The file metadata should not change

### Actual behavior

The file is created new with its "created" metadata being the same as "last changed".

It is not actually edited it seems, at least when "editing a file" i.e. overiting the existing file.

**Comment by Aga-C** [comment]
It's another case of an already raised bug about losing metadata: https://github.com/FossifyOrg/Gallery/issues/29.
