### ISSUE TITLE
Error: java.lang.SecurityException

### ISSUE THREAD

**Issue by QuestioningEspecialy** [FossifyOrg/Gallery#156]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

v1.1.1

### Affected Android/Custom ROM version

Android 14 / GrapheneOS

### Affected device model

Pixel 6a

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

open/select any image -> press edit icon on the bottom of the screen or the button in the 3-dot dropdown on the top right

### Expected behavior

edit window opens

### Actual behavior

error code appears on bottom of screen that reads...

> Error: java.lang.SecurityException: UID 10100 does not have permission to co...

**Comment by Aga-C** [comment]
1. Haven't you removed any permissions for Gallery?  
2. Is the file on the phone's internal or external memory (SD or USB)?

**Comment by naveensingh** [comment]
@QuestioningEspecialy have you tried allowing All files access? 

Settings -> Apps -> Special app access -> All files access -> FG -> Allow.

**Comment by Aga-C** [comment]
@QuestioningEspecialy Check Privacy -> Permission Manager, and then probably Files.
