### ISSUE TITLE
Cloudinary integration

### ISSUE THREAD

**Issue by diomed** [FossifyOrg/Gallery#168]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I would like Cloudinary integration 

### Why do you want this feature?

I want this feature so I can upload images to Cloudinary and have them available online when needed.
I usually need them to be uploaded so I can access them on another device, like on PC.

Would be great for backup.

**Comment by Aga-C** [comment]
By the design, app has no Internet access, so we can't do this.
