### ISSUE TITLE
[fr] mute videos

### ISSUE THREAD

**Issue by throwaway242685** [FossifyOrg/Gallery#171]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

there should be an option, something like "Mute videos", to be able to play videos without sound.

<img alt="screenshot_20240320-155421" src="https://github.com/FossifyOrg/Gallery/assets/85243826/49499d1e-3217-4d42-bce2-a7faf702d7fc" width=452 />

### Why do you want this feature?

pretty much every player has something like this.

**Comment by naveensingh** [comment]
I think this belongs in the player control UI, not the settings.

**Comment by throwaway26425** [comment]
well, I meant to open videos as muted by default. (?)

as long as that button is persistent, I'm okay with that.

**Comment by throwaway26425** [comment]
are there any plans to implement this?

**Comment by naveensingh** [comment]
Yes, it'll be likely be added in the next release (whenever that is).

**Comment by naveensingh** [comment]
<img src="https://github.com/user-attachments/assets/12b10d43-4148-4ea5-9c53-e39af5fe3162" width=200 /> <img src="https://github.com/user-attachments/assets/67819c4b-b94a-4d10-b66c-7ad2d661a732" width=200 />

Added a simple mute button. Like the volume control gesture, the mute button directly affects and is in sync with the system music stream volume.

**Comment by tswistak** [comment]
> the mute button directly affects and is in sync with the system music stream volume.

@naveensingh Why? I just tested the newly released version, and this behavior is very counterintuitive, I don't know any other app that works like this. All players that I know mutes only on their level, not on the whole system. What's worse, unmuting brings system volume to 100%. I wanted to raise it as a bug, but found this comment, and I'm a bit confused.

**Comment by naveensingh** [comment]
I assumed people might be accustomed to that because the volume control gesture works similarly. I don't use VLC much but volume control there is also linked with system.

Linking the system volume and player volume allows us to properly update the UI when you change/mute volume using system wide options like the hardware volume keys.

**Comment by throwaway242685** [comment]
I don't know if that's a technical limitation of the old code of Simple Gallery, but [Next Player](https://f-droid.org/packages/dev.anilbeesetti.nextplayer) can mute videos without muting the whole system.

the volume there is also linked to the system volume, as far as I know.

when I suggested this feature I actually did it on favor of listening to music in the background while watching muted videos :) so, yeah... I also think that the mute feature should be only at app level, not at system level.

**Comment by naveensingh** [comment]
| Case                                                      | Default Behavior                                    | Linked Behavior                                    |
|-----------------------------------------------------------|-----------------------------------------------------|--------------------------------------------------------|
| **1. Volume changes while player is muted**        | Player remains muted          | Unmute player?     |
| **2. Volume increases from zero while player is muted**         | Player remains muted          | Unmute player               |
| **3. Volume set to zero while player is not muted**        | Player remains unmuted (no sound)      | Player is muted         |


I'm going with the default behavior.

**Comment by throwaway242685** [comment]
it would be great if the muting feature was persistent.

e.g. next time that you open a video, it should remember if the player was muted or not, and then use that.

**Comment by naveensingh** [comment]
yeah, it'll be persistent.
