### ISSUE TITLE
Add option to load all thumbnails at startup and don't unload them

### ISSUE THREAD

**Issue by soredake** [FossifyOrg/Gallery#174]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

It will be nice to have option to load all thumbnails at startup and don't unload them, like in this app https://play.google.com/store/apps/details?id=com.google.android.apps.photosgo

### Why do you want this feature?

I love to scroll my images fast, and i don't love seeing them loading on-demand or unloading when i scroll.

**Comment by Aga-C** [comment]
Would this be enough for you: https://github.com/FossifyOrg/Gallery/issues/136?

**Comment by soredake** [comment]
If disabling this "fade-in" effect will mean that all thumbnails are always loaded (as startup) too, then yes.
