### ISSUE TITLE
Auto empty Recycle Bin

### ISSUE THREAD

**Issue by abuturabofficial** [FossifyOrg/Gallery#180]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

There should be some kind of auto deletion feature for recycle bin, may be ranging from 7 to 30 days.

### Why do you want this feature?

To make redundant storage usable.

**Comment by Aga-C** [comment]
Files are automatically removed from the recycle bin after 30 days (see in-app FAQ, 14th entry).
