### ISSUE TITLE
Crashes on saving an image filter

### ISSUE THREAD

**Issue by chriswere** [FossifyOrg/Gallery#181]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.2

### Affected Android/Custom ROM version

13

### Affected device model

Nokia C32

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Apply a filter to a photograph
2. Save photograph
3. No save file is made and no changes are saved
4. App is still running but looks like it quickly shutdown and re-opened.

### Expected behavior

The filter is saved as a new file, or overwritten as existing one.

### Actual behavior

No file is saved.

**Comment by Aga-C** [comment]
1. Are you sure that while opening editor, the opened editor is Fossify Gallery's editor? I'm asking because if there isn't any set as default, the app asks whether to use the built-in editor or other app in the system for this.
2. `No save file is made and no changes are saved` - if you use Fossify Gallery's built-in editor, it asks during save where to save and under what name. Please double-check, maybe it got saved.

**Comment by chriswere** [comment]
I've just had a play around. It seems to be a specific image it's having the issue with, so it seems likely that it's the image at fault. I just tried to recreate the issue with a new image and it worked. I think i can close this issue.
