### ISSUE TITLE
Inaccurate translation (Spanish)

### ISSUE THREAD

**Issue by fabian19vs** [FossifyOrg/Gallery#189]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.3

### Affected Android/Custom ROM version

GrapheneOS (android 14)

### Affected device model

Pixel 7

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Just open the app and see the month view or week view.
I tried to find the string causing this mistake on the strings file but didn’t find it.

### Expected behavior

The shortened word for “Sábado” (Saturday) is “Sáb.”  But it should be better if just “S”, as in the other days on the calendar.
The days on the calendar should be D-L-M-X-J-V-S. (With Sunday[domingo] as the first day of the week)

### Actual behavior

The days appear as follows:
D-L-M-X-J-V-Dom.
Which is incorrect because D and Dom are the same day (Sunday).
The behavior persists if I set Monday (lunes) as the first day of the week.

### Screenshots/Screen recordings

<img alt="IMG_0064" src="https://github.com/FossifyOrg/Gallery/assets/96337534/0082fa6c-8d8b-433f-b82c-a94677568a8a" width=599 />

**Comment by Aga-C** [comment]
Here you can fix it: https://hosted.weblate.org/translate/fossify/commons/es/?checksum=438250412d8f0998&q=saturday_letter&sort_by=-priority%2Cposition#history.
