### ISSUE TITLE
Moving Folders into Another Removes Folder Structure

### ISSUE THREAD

**Issue by neo-neo1** [FossifyOrg/Gallery#190]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.2

### Affected Android/Custom ROM version

Android 13 / Stock Rooted Moto Rom

### Affected device model

Moto G Stylus 2023

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Moving or copying Folder A (with photos inside) into Folder B just moves the photos without the folder structure. It does not preserve the folder structure.

### Expected behavior

i.e. 
Moving /Internal/Pictures/Folder_A (with photos inside) into /Internal/Pictures/Folder_B SHOULD BE /Internal/Pictures/Folder_B/Folder_A (with photos inside). However it currently instead moves photos from /Internal/Pictures/Folder_A into /Internal/Pictures/Folder_B.

### Actual behavior

This becomes even more problematic if moving or copying 2 folders into another folder.
Again, it doesn't preserve the folders, instead it moves photos from both source folders into a single destination folder. Without creating new folders into where you're moving, folder hierarchy is not perserved.

### Additional information

Can this please be fixed? Or at least an option to toggle? This isn't how Samsung Gallery works which is what I'm used to. Not being able to preserve folder structure when moving or copying is a big deal for my use case - and I presume many others. Thanks in advance.

**Comment by Aga-C** [comment]
Gallery is not a file management app, so it doesn't operate on a concept of folders, it treats them as albums. That's why moving is moving whole album content into another, not a directory to another. If it moved directories, it would be confusing on the default view, where you don't have the folder hierarchy preserved.

**Comment by neo-neo1** [comment]
> Gallery is not a file management app, so it doesn't operate on a concept of folders, it treats them as albums. That's why moving is moving whole album content into another, not a directory to another. If it moved directories, it would be confusing on the default view, where you don't have the folder hierarchy preserved.

Basic file management in a gallery app is expected. 

If your gallery app can create, copy, and move folders you should be able to properly move folders structures. It's an basic good practice in file management 101. Preserve folder structure when copying.

Looks like it's back to Samsung Gallery I go.
