### ISSUE TITLE
Creating New Folders Hierarchy Not Preserved

### ISSUE THREAD

**Issue by neo-neo1** [FossifyOrg/Gallery#191]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.2

### Affected Android/Custom ROM version

Android 13 / Stock Rooted Moto Rom

### Affected device model

Moto Stylus 

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

When viewing inside a folder: /Internal/Pictures/Folder_A and creating new a folder: Folder_B the new folder gets created into /Internal/Pictures/Folder_B

### Expected behavior

It should have created Internal/Pictures/Folder_A/Folder_B

### Actual behavior

N/A

### Additional information

This seems like a straight forward bug. This app doesn't create a folder inside a folder when asked.

**Comment by Aga-C** [comment]
I can't reproduce the problem. I checked with external file manager and with grouping view - it's always created where it should be. Please provide more detailed reproduction steps by filling properly `Steps to reproduce the bug`, `Expected behavior` and `Actual behavior`.
