### ISSUE TITLE
Videos are always opened using an external app, therefore "Open videos in an external application" is not checked in preferencies

### ISSUE THREAD

**Issue by brunetton** [FossifyOrg/Gallery#195]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.2

### Affected Android/Custom ROM version

Andoid 11

### Affected device model

Google Pixel 5

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. make sure Parameters -> Videos -> Open videos in an external app is **disabled** (unckecked)
2. click on a video on gallery

### Expected behavior

The video should be played in the app

### Actual behavior

Android asks for selecting an app to open the video, I've to select Fossily Gallery every time

**Comment by Aga-C** [comment]
> make sure Parameters -> Videos -> Open videos in an external app is disabled (unckecked)

It seems to be a wrong translation in your language (French, I assume?). That option is about opening videos in a different UI supporting gestures, not in an external app. If you'd like, you can fix it on [Weblate](https://hosted.weblate.org/translate/fossify/gallery/fr/?checksum=548b015706cd887f&q=open_videos_on_separate_screen&sort_by=-priority%2Cposition).

Also, in that system window, you can always set Fossify Gallery as a default video app.

**Comment by brunetton** [comment]
Thanks for your quick and detailed answer !

> It seems to be a wrong translation in your language (French, I assume?). That option is about opening videos in a different UI supporting gestures, not in an external app. If you'd like, you can fix it on [Weblate](https://hosted.weblate.org/translate/fossify/gallery/fr/?checksum=548b015706cd887f&q=open_videos_on_separate_screen&sort_by=-priority%2Cposition).

Ideed ! What a mess here ;) I totally missed this possibility of horizontal gestures. If I can suggest, the original parameter name `Always open videos on a separate screen with new horizontal gestures` is not clear either IMHO. If you are akay I could propose a PR to replace it with something else, like `Use horizontal gestures to scroll in videos`

> Also, in that system window, you can always set Fossify Gallery as a default video app.

For some reason, Android doesn't gives me the choice for using this app every time here. No "always use this app" button :s I tried with other softwares and start to think that it's not related to FossifyOrg Gallery:
- [Little File Explorer](https://f-droid.org/packages/com.martinmimigames.simplefileexplorer/) => same problem
- ["File explorer"](https://github.com/Raival-e/File-Explorer) => same problem
- [Amaze file explorer](https://play.google.com/store/apps/details?id=com.amaze.filemanager&hl=fr&gl=US) => strangely here the button appears. I don't know if I see the Android's UI or app specific UI here

I'll continue to investigate on this particular point.

Thank you

**Comment by naveensingh** [comment]
It should be rephrased but I don't think "scroll" is the right word here.  When "Always open videos on a separate screen with new horizontal gestures" is enabled:
- Videos do open on a separate screen.
- Horizontal gestures are used for video seeking.

We could do "Enable horizontal gestures to seek in videos" or  "Enable horizontal gestures for video seeking" but still, the 'separate screen' part is not clarified. I'll think about this.

**Comment by brunetton** [comment]
> It should be rephrased but I don't think "scroll" is the right word here. When "Always open videos on a separate screen with new horizontal gestures" is enabled:
> 
> * Videos do open on a separate screen.
> * Horizontal gestures are used for video seeking.
> 
> We could do "Enable horizontal gestures to seek in videos" or "Enable horizontal gestures for video seeking" but still, the 'separate screen' part is not clarified. I'll think about this.

I don't get the "separate screen". I'm using Fossily Gallery on an Android phone, so I have one screen. Is this feature for devices with more than one screen ? Or I'm totally missing something ?

Thanks
