### ISSUE TITLE
Some colors do not render correctly after updading to 1.1.3

### ISSUE THREAD

**Issue by Vsnmrn** [FossifyOrg/Gallery#202]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung A54

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open the app
2. Open the app settings
3. Then open the about

### Expected behavior

The colors should not have changed.

### Actual behavior

Some colors render differently depending on whether you are in the app settings or in the about.

### Screenshots/Screen recordings

At the left it is 1.1.2, at the right it is 1.1.3. The settings page does not change, it is the reference. (For exemple the titles in the about have a different color than the titles in the settings in 1.1.3)
<img alt="image119" src="https://github.com/FossifyOrg/Gallery/assets/146990829/6aa4ff95-e4fb-41ac-a4b1-a151c23afa5e" width=145 />

### Additional information

I've found 2 similar problems here :
https://github.com/FossifyOrg/Gallery/issues/94
https://github.com/FossifyOrg/General-Discussion/issues/85
But these issues where linked to the old orange accent color and are supposed to be fixed now.

**Comment by naveensingh** [comment]
The slight accent color difference between the about page and other pages are because of color tone variations between the XML theme and jetpack compose theme.

The about page was rewritten in jetpack compose a while ago, everything else still uses the view system.

But this difference should already be there in every Fossify app. Not just the Gallery.
