### ISSUE TITLE
Ascending/descending sorting options don't work properly when choosing to group by

### ISSUE THREAD

**Issue by serrq** [FossifyOrg/Gallery#207]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

OnePlus CPH2399

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Sort by "last modified"
2. Select ascending or descending

Nothing happens. See the exactly position of the images. The last month always shown at the bottom.

### Expected behavior

Sort months upsidedown.

### Actual behavior

Nothing change.

**Comment by Aga-C** [comment]
`Sort by` option works within the group. If you want to sort groups, in `Group by` you can set, whether they should be sorted ascending or descending.

**Comment by Aga-C** [comment]
Have you set `Descending` in `Group by`?
