### ISSUE TITLE
Copy, Move & delete function Show progress dialog

### ISSUE THREAD

**Issue by AdityaMishra135** [FossifyOrg/Gallery#22]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by naveensingh** [comment]
Please fill the template.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/FossifyOrg/Gallery/issues/22#issuecomment-1868522203

@naveensingh, unless this feature already exists, surely the title is enough to at least understand the FR? I can repost one with a filled template if of use.

**Comment by Aga-C** [comment]
@RokeJulianLockhart So, please create a new feature request with a properly filled template.
