### ISSUE TITLE
Disable scanning for picture files, add selecting Folders to include

### ISSUE THREAD

**Issue by RealVegOs** [FossifyOrg/Gallery#228]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Please implement an option to disable automatically adding all folders with pictures to gallery. If this option is enabled, there should be a dialog to select folders manually. 

### Why do you want this feature?

I have a lot of png files from another app. These are map previews. This app also creates new folders and I do not want them to show up in the gallery.

**Comment by Aga-C** [comment]
Check the 10th entry in the FAQ.

**Comment by RealVegOs** [comment]
> Check the 10th entry in the FAQ.

OK, thats working too, but for me it woulde be more elegant to choose folders instead of excluding those you don't want to see. BTW, I hate Android and the best app would not make it better. Cheers!
