### ISSUE TITLE
Browser individual folder 

### ISSUE THREAD

**Issue by AdityaMishra135** [FossifyOrg/Gallery#234]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Every folder parent path individual browser. Similar like group folder but its Starting from /storage/... path l

### Why do you want this feature
It's Same as GROUP function but here do group like /storage/emulated/0/ not do like /storage/emulated/0/camera have 2 children path.

### Additional information

How can I do this please give any suggestion

**Comment by Aga-C** [comment]
Is your request the same as this: https://github.com/FossifyOrg/Gallery/issues/150? If not, please explain how it's different.
