### ISSUE TITLE
Add a mode for displaying all folders, regardless of whether they contain media or not

### ISSUE THREAD

**Issue by Korb** [FossifyOrg/Gallery#235]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I need to be able to see all folders, not just the ones that have media files in them.

### Why do you want this feature?

Currently I can only move images to a folder that already contains images. Consequently, I can't move or copy images to a folder such as an empty Download folder or a newly created one because it won't show up in the folder browser.

**Comment by naveensingh** [comment]
You can pick any folder using the "**Other folder**" button in the copy/move dialog.

**Comment by Korb** [comment]
@naveensingh, you are right, such situations are provided for by the functionality of the application. I was choosing an application on F-Droid for managing images on a smartphone, and Fossify Gallery seemed to me one of the most attractive. But from the presented screenshots, I made the wrong conclusion that what is not shown in them is not in the application. I ask that this ticket be closed as an error, and I ask that screenshots be added to F-Droid in which the functionality of the application will be presented more fully.

**Comment by naveensingh** [comment]
Generally, I think the right approach is install and try an app, screenshots and descriptions aren't always up to date. Also, App stores often a limit on the number of screenshots you can upload so we can't showcase all features using screenshots.
