### ISSUE TITLE
Showing image file types on thumbnails broken

### ISSUE THREAD

**Issue by VadosG** [FossifyOrg/Gallery#236]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 13

### Affected device model

Nubia Neo 5G

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

In "Settings -> File thumbnail style -> Show image file types" do nothings

### Expected behavior

-

### Actual behavior

-

### Screenshots/Screen recordings

<img alt="bug" src="https://github.com/FossifyOrg/Gallery/assets/132702182/d89bfc60-4c03-413b-9dfe-bb318b94b72d" width=188 />

**Comment by Aga-C** [comment]
It's an expected behavior. This setting only shows in a thumbnail if the file is RAW, SVG or GIF.

**Comment by VadosG** [comment]
Oh, misunderstanding. Thank you.
