### ISSUE TITLE
Automatically reload folder list after creating a folder

### ISSUE THREAD

**Issue by Lppsoeht** [FossifyOrg/Gallery#243]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

The folder I created should appear in the folder list without manually reloading the folder list.

### Why do you want this feature?

After creating a new folder(with copy/move to -> other folder -> create new folder) the folder should right away appear in the dashboard.
Right now if I don't reload the gallery folder list manually the folder doesn't appear, it's like it's not part of the app.

**Comment by Aga-C** [comment]
Currently, it's working just as you described - on the app's main screen, a new folder appears instantly after copying a file to it. It seems to be a bug on your device, or you're doing some specific action in-between. Please fill a [bug report](https://github.com/FossifyOrg/Gallery/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=bug_report.yml) writing as many details as you can.
