### ISSUE TITLE
Toggle to stop showing extended details by default

### ISSUE THREAD

**Issue by Lppsoeht** [FossifyOrg/Gallery#245]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

A toggle to stop showing most of the UI when it overlaps portion of a picture/video.
Filename is really not needed to be seen most of the times. I know I can click once to make all the UI disappear but users should choose themselves the default behaviour

### Why do you want this feature?

Sometimes I just need to see high-resolution pictures or screenshots and most of the UI is useless and gets in the way.

**Comment by Aga-C** [comment]
It's already in Settings → `Automatically hide system UI at fullscreen media`.
