### ISSUE TITLE
Gallery cause com.google.android.providers.media.module keep running in high CPU

### ISSUE THREAD

**Issue by GHolk** [FossifyOrg/Gallery#256]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 13

### Affected device model

Fairphone 4

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Put a lot of file in a folder in sdcard or somewhere, and add a `touch .nomedia` in the folder. (I put about 10G and 80000 no-media files)
2. Launch the Fossify Gallery.
3. Grant Fossify Gallery the permission to manage all files in storage in dialog inside gallery.
4. Get redirected to the app permission page, and there is only **Manage Media** permission. Grant it.
5. Go back to the Fossify Gallery.

### Expected behavior

I put a nomedia in the folder so fossify gallery should not scan that folder.

### Actual behavior

1. The phone heat up. Running `top` in adb shell show that `com.google.android.providers.media.module` run in high CPU (100~300%).
2. killing the app stop com.google.android.providers.media.module running in high cpu.

### Screenshots/Screen recordings

```
Tasks: 850 total,   2 running, 840 sleeping,   0 stopped,   0 zombie    
  Mem:  8000000K total,  7500000K used,   400000K free,   100000K buffers                                                                        
 Swap:  4000000K total,  2000000K used,  1000000K free,  1000000K cached                                                                         
800%cpu  70%user  80%nice  70%sys 550%idle   0%iow   6%irq   1%sirq   0%host                                                                     
  PID USER         PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS                                                                             
 4000 u0_a100      20   0  16G 111M  37M S  169   1.4  57:05.80 com.google.android.providers.media.module                                        
28167 u0_a101      10 -10  16G 258M 120M S 51.0   3.4   0:30.81 org.fossify.gallery                                                              
   94 root         20   0    0    0    0 S  5.0   0.0   1:09.96 [kswapd-1:0]                                                                     
29613 root         20   0    0    0    0 I  3.0   0.0   0:06.36 [kworker/u16:4-memlat_wq]                                                        
29589 root         20   0    0    0    0 I  2.0   0.0   0:05.44 [kworker/u16:0-memlat_wq]                                                        
 1439 system       18  -2  20G  63M  63M S  1.6   0.8  10:43.40 system_server                                                                    
30419 shell        20   0  12G 4.9M 3.1M R  1.3   0.0   0:00.33 top     
 1017 system       20   0  12G 4.5M 3.1M S  1.0   0.0   0:48.73 android.hardware.sensors@2.0-service.multihal                                    
 2555 u0_a102      20   0  17G 188M  88M S  0.6   2.5   4:07.15 com.android.systemui                                                             
   17 root         RT   0    0    0    0 S  0.6   0.0   0:31.53 [migration/0]                                                                    
```

### Additional information

In fact, I am not sure whether Gallery cause this bug,
and lsof (with root) does not show that gallery or providers.media.module is reading the folder.

**Comment by Aga-C** [comment]
Do you have the same problem while running other gallery apps?

**Comment by kontakt1-art** [comment]
[](url)

**Comment by kontakt1-art** [comment]
### `**SearchIndexableResources**`

**Comment by GHolk** [comment]
It might relate to the new storage access framework from android-11.
Some syncthing users (a p2p software) report similar issues:

https://forum.syncthing.net/t/scanning-syncing-with-syncthing-android-is-extremely-slow-1570/15770
https://forum.syncthing.net/t/syncthing-fork-slow-due-to-android-filesystem-abstraction-layer/24040

There is no workaround now.

**Comment by haldi4803** [comment]
> ### Additional information
> 
> In fact, I am not sure whether Gallery cause this bug, and lsof (with root) does not show that gallery or providers.media.module is reading the folder.

I will tell you really soon....

Been plagued by media picker Service for 2-3 days now!
Uninstalled gallery. Let's see if that helps. 

<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/998a48c4-6f69-4936-86cd-94582beca890" width=180 />
<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/ec33ccad-70d8-4037-a28c-b75c6c0f0ac9" width=180 />
<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/acae5b16-c2e1-4db6-834b-d8e792d92005" width=180 />
<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/c831354c-1a5e-46f8-8a40-62ccf62110cf" width=367 />
<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/d28e0fb3-acd8-476f-8fb3-94749be3f17e" width=400 />

**Comment by haldi4803** [comment]
Yep...
After uninstalling gallery that looks way better!

The thing is, I have this "excluded folder" with freshly downloaded mangas. Yet it still triggered the Media Picker. 

<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/130dfb38-4a57-49a4-9686-9c72ae02cdd6" width=180 />
<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/37a23027-db4e-40bf-a7ba-333b47a46c56" width=180 />
<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/9e37729d-e80a-4bff-902e-71725963b940" width=180 />
