### ISSUE TITLE
PocketPaint / Paintdroid Integration

### ISSUE THREAD

**Issue by Maxitendo1** [FossifyOrg/Gallery#257]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I'm using Pocket Paint for editing my images and it's a better alternative to Adobe Photoshop.

### Why do you want this feature?

It would be nice to see Pocket Paint in the Fossify Gallery app because I think that the gallery editor is too plain.

**Comment by Aga-C** [comment]
We are planning to extend editor functionality to be similar to advanced editor from Simple Gallery Pro. We don't plan using any third party apps.
