### ISSUE TITLE
Column count menu item is redundant

### ISSUE THREAD

**Issue by Riksu9000** [FossifyOrg/Gallery#265]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

You can change the column count with pinch to zoom. This makes the column count option redundant.

### Why do you want this feature?

Having a menu with too many options is bothersome to use and will deter users.

### Additional information

Having fewer options in the menu in general would improve the user experience.

**Comment by naveensingh** [comment]
I don't think it should be removed because pinch to zoom isn't reliable enough as of now and not everyone is aware of it.
