### ISSUE TITLE
No scrollbar in settings

### ISSUE THREAD

**Issue by Riksu9000** [FossifyOrg/Gallery#266]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Lineageos 21

### Affected device model

Xperia 5 III

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

Open settings and scroll around

### Expected behavior

There should be a scrollbar that displays the current position in the settings screen.

### Actual behavior

There is no scrollbar

**Comment by Aga-C** [comment]
Please raise issues regarding all apps in https://github.com/FossifyOrg/General-Discussion/issues.

**Comment by Riksu9000** [comment]
Maybe the issue should be transferred, or kept open for reference.

**Comment by naveensingh** [comment]
@Riksu9000 

Thanks for raising the issue.

> issue should be transferred

We don't do that because then we'll have to transfer each and every issue that belongs to the general repository but raised somewhere else.

> kept open for reference

Not necessary as there's no important discussion here yet and even then a link is sufficient in most cases.
