### ISSUE TITLE
Capture Date sometimes not honored, but modification date used instead.

### ISSUE THREAD

**Issue by george84** [FossifyOrg/Gallery#267]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

OPPO reno 8 5G

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

Go to display list of photos. Note the date of group. Click on a photo in group and show info. -> capture date does not match group date.
This only occurs on some files. I had the impression that photos with GPS info are correct.

### Expected behavior

I expect the photos to be grouped by capture date.

### Actual behavior

Sometimes they are grouped by file date
On screenshots you see the photos grouped under 8.6.2015. If you look at detail of third photo it displays capture date 7.5.2013. This means the photo has the correct capture date (EXIF and IPTC info)
I made sure that in settings I had selected "group by capture date". 

### Screenshots/Screen recordings

![Screenshot_2024-07-22-18-00-47-06_88ecc4b3b334cca6fa7678692a75c1df](https://github.com/user-attachments/assets/877f90f8-6a6b-47f5-b81b-4f175593b19a)
![Screenshot_2024-07-22-18-01-20-72_88ecc4b3b334cca6fa7678692a75c1df](https://github.com/user-attachments/assets/259b6eba-f623-4861-a8e0-449bb00ae650)

### Additional information

![2013_0507_070248AA](https://github.com/user-attachments/assets/4c125bef-932b-47df-9770-2d9d0812bacb)

**Comment by Aga-C** [comment]
Have you tried selecting images with wrong grouping and using `Fix date taken` in three dots menu?

**Comment by george84** [comment]
Thank you for fast reply.
Using 

> Fix date taken

 will fix problem. By doing **Select all** it will even fix **all pictures**.

Further analysis shows that the original files are not modified by this fix. Searching problems in Simple Gallery I found that many people had similar problem.
Can you please give a hint where in your code this fix happens so that I could possibly adapt the original files so that they are displayed correctly without having to use the fix. Master for photos is on a Windows machine and smartphone is only used to show photos to friends.

**Comment by Aga-C** [comment]
It doesn't modify files, it just updates metadata in Android's media store. Sometimes it doesn't have proper data when files aren't created on the same device. Here's the code: https://github.com/FossifyOrg/Gallery/blob/eefe0b65aff469ac621f604eb1a06140bf2f226c/app/src/main/kotlin/org/fossify/gallery/extensions/Activity.kt#L530.
