### ISSUE TITLE
Cant set picture as lock screen wallpaper

### ISSUE THREAD

**Issue by truong0235** [FossifyOrg/Gallery#273]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

 Miui 13.0.16 stable, android 11

### Affected device model

Poco C40

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

-choose a random image
-tap 3 button from top right, tap set as
-tap the check button on the top left
-choose lock screen option or home screen and lock screen

### Expected behavior

It should change the lock screen to selected image

### Actual behavior

Lock screen doesnt change at all (only home screen if home screen and lock screen option is selected)

**Comment by Aga-C** [comment]
1. After selecting to set an image as a lock screen image, do you see the toast message `Setting wallpaper` and then `Wallpaper set successfully`?
2. Can you set an image as a lock screen image with any other app than Fossify Gallery?

**Comment by Aga-C** [comment]
Don't worry, I'm glad I could help.
