### ISSUE TITLE
force Material You Dark color scheme

### ISSUE THREAD

**Issue by kitsuragi** [FossifyOrg/Gallery#285]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

the app allows me to choose freely between generic light/dark themes, but for material you, i only have an option to choose the system default light/dark setting

### Why do you want this feature?

i almost never use dark mode system-wide, but i do prefer it in media apps like youtube, gallery etc to have fewer distractions and more immersion into visual content i'm browsing, so it would've been very convenient to have that option in the app for material you color scheme, if it's possible, of course

**Comment by Aga-C** [comment]
Please raise issues regarding all apps in https://github.com/FossifyOrg/General-Discussion/issues.
