### ISSUE TITLE
Option to switch default search from "folders" to "filenames"

### ISSUE THREAD

**Issue by jeremymeyers** [FossifyOrg/Gallery#292]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I hardly ever have a need to search folder names when first opening the app but i do search for files by name a lot so each time i have to enter my search, then click "search for files" then enter again.

### Why do you want this feature?

Having a way to shift the default search would save a step of a task i do almost every time i use the app.

### Additional information

Alternatively, maybe it could be one search that covers both folder names and files?

**Comment by Aga-C** [comment]
It's already in the app. Enable `Search all files instead of folders on the main screen` in Settings.
