### ISSUE TITLE
Incorrect sorting

### ISSUE THREAD

**Issue by spal54** [FossifyOrg/Gallery#296]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.3

### Affected Android/Custom ROM version

Android 14

### Affected device model

Motorola Edge 50 Ultra

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Select any folder
2. Select sorting icon in top right
3. Sort by - Date taken

### Expected behavior

Photos and videos should be sorted by Date taken field

### Actual behavior

Photos and videos are sorted by Last modified field

**Comment by Aga-C** [comment]
Check the second entry in the app's FAQ.

**Comment by Artiom-M** [comment]
I totally disagree with Invalid label. Date taken is an EXIF metadata field. Are you may assuming it is equal to modified date? Because this one can be updated by an editing tool, by some copy, etc. While EXIF field is generally preserved. 
I would suggest to remove the "Sort by date taken" option is order to avoid confusion or implement it properly. FAQ propose to "Fix date taken" that I would not touch, because for me:

1. It is not wrong, so nothing to fix
2. It is not a solution but a workaround.

**Comment by naveensingh** [comment]
Here's some info regarding why it's done this way: https://github.com/FossifyOrg/Gallery/issues/88#issuecomment-1901193363

**Comment by Artiom-M** [comment]
Well this helps, thank you. Still as I understand it can happen again, when I will add more external photos. So still not the best solution.
