### ISSUE TITLE
Folders randomly disappear

### ISSUE THREAD

**Issue by yephny** [FossifyOrg/Gallery#298]
As the title says, folders randomly disappear and show up sometimes days later. Today, for instance, I couldn't find my Favorites folder.

**Comment by yephny** [comment]
@Aga-C Are you using the new (not sure if it's in beta) issue templates feature? The old one works fine with OctoDroid but if it's the new one I don't see a template anywhere.

**Comment by naveensingh** [comment]
Yes, we are using issue forms.

**Comment by asgsdbrseg** [comment]
I also encountered it, but couldn't reproduce it, the latest version

**Comment by asgsdbrseg** [comment]
https://d.kuku.lu/u7yyj5y8s

As shown in the video, I don't know why it disappeared or why it appeared
