### ISSUE TITLE
Freezing when scrolling in the new version

### ISSUE THREAD

**Issue by Pushkin31** [FossifyOrg/Gallery#301]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

Android 14, oxygenOS 14

### Affected device model

OnePlus 12

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open the application 
2. Open any folder with many media files (photos+videos)
3. Scroll

### Expected behavior

Scrolling without freezing, file previews load quickly

### Actual behavior

When scrolling, the application freezes, it takes a long time to load file previews. Until all previews in the folder are loaded, it does not open any photo/video

### Screenshots/Screen recordings

Log file
[crash-org-fossify-gallery-22_09-12-46-12_347.zip](https://github.com/user-attachments/files/17089057/crash-org-fossify-gallery-22_09-12-46-12_347.zip)

**Comment by naveensingh** [comment]
Thanks for the logs!

Is anyone else able to reproduce this?

**Comment by Aga-C** [comment]
Exactly how many files do you have in a folder where you experience this problem?

**Comment by Pushkin31** [comment]
> Exactly how many files do you have in a folder where you experience this problem?

It can also freeze on the main screen. Freezing occurred in a folder with more than 700 media. Previews load slowly even in a folder with 80 media, but scrolling does not slow down

**Comment by Pushkin31** [comment]
> Exactly how many files do you have in a folder where you experience this problem?

It can also freeze on the main screen. Freezing occurred in a folder with more than 700 media. Previews load slowly even in a folder with 80 media, but scrolling does not slow down

**Comment by naveensingh** [comment]
I can reproduce this 'occasionally' on a Samsung device.

**Comment by BluePixel4k** [comment]
> Is anyone else able to reproduce this?

I also notice this issue frequently.
(Pixel 8 with GrapheneOS (A14))

**Comment by AdityaMishra135** [comment]
Yes, I'm also facing this.

**Comment by Aadesh001** [comment]
Facing this on Nothing Phone 2 (Nothing OS 2.6, Android 14) frequently

**Comment by naveensingh** [comment]
It might help if anyone would share the file exported by Gallery => Settings => Export settings.

**Comment by Pushkin31** [comment]
> It might help if anyone would share the file exported by Gallery => Settings => Export settings.

I am attaching the file

![gallery-settings_2024_09_23_11_29_44.txt](https://github.com/user-attachments/files/17094624/gallery-settings_2024_09_23_11_29_44.txt)

**Comment by nexxus-vi** [comment]
+1 on Pixel 7  -  14 (AP2A.240705.004)
[gallery-settings_2024_09_23_15_39_23.txt](https://github.com/user-attachments/files/17098456/gallery-settings_2024_09_23_15_39_23.txt)

**Comment by Mape6** [comment]
+1 Pixel 7a
I killed the app, cleaned the cache and started the app again. The first thumbnails are generated quickly and after some the process slows down quickly.

**Comment by naveensingh** [comment]
Seems to be caused by JPEG XL support added in https://github.com/FossifyOrg/Gallery/pull/253

If you guys are up for testing, here's an APK with the above change reverted: [gallery-8-foss-release.apk.zip](https://github.com/user-attachments/files/17113733/gallery-8-foss-release.apk.zip)

Please remove the .zip extension from the filename, thanks!

**Comment by vivident4004** [comment]
> +1 Pixel 7a I killed the app, cleaned the cache and started the app again. The first thumbnails are generated quickly and after some the process slows down quickly.

Exactly this, and it struggles to the point of freezing especially with animated media (.mp4, .mov, .webp) when trying to load or create thumbnails.
Here's my settings file:
[gallery-settings_2024_09_24_14_39_29.txt](https://github.com/user-attachments/files/17114711/gallery-settings_2024_09_24_14_39_29.txt)

**Comment by Mape6** [comment]
> Seems to be caused by JPEG XL support added in #253
> 
> If you guys are up for testing, here's an APK with that change reverted: [gallery-8-foss-release.apk.zip](https://github.com/user-attachments/files/17113733/gallery-8-foss-release.apk.zip)
> 
> Please remove the .zip extension from the filename, thanks!

That version works perfectly.

**Comment by naveensingh** [comment]
@Mape6 Thanks for testing!

**Comment by vivident4004** [comment]
> Seems to be caused by JPEG XL support added in #253
> 
> If you guys are up for testing, here's an APK with that change reverted: [gallery-8-foss-release.apk.zip](https://github.com/user-attachments/files/17113733/gallery-8-foss-release.apk.zip)
> 
> Please remove the .zip extension from the filename, thanks!

For me, this seems to have solved the issue. I even cleared the cache once more to force the app to rebuild the thumbnails, and scrolling in a folder full of movies it has no issues now, while before it freezed and crashed.
Tested on a Pixel 7 with GrapheneOS with Android 14 2024091900.

**Comment by shockergit** [comment]
Yes its even the thumbails are loading after 2 minutes. Image loading takes lot of time. While switching back to simple gallery it works fine.

**Comment by naveensingh** [comment]
Should be fixed in version 1.2.1: https://github.com/FossifyOrg/Gallery/releases/tag/1.2.1

**Comment by shockergit** [comment]
> Should be fixed in version 1.2.1: https://github.com/FossifyOrg/Gallery/releases/tag/1.2.1

I think this fixed
