### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [FossifyOrg/Gallery#302]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

None

### Affected device model

None

### How did you install the app?

None

### Steps to reproduce the bug

https://gitlab.com/fdroid/fdroiddata/-/jobs/7888189897 JCenter has gone... We can't use libs in it anymore. Please migrate away from it, thanks!

### Expected behavior

JCenter is not used.

### Actual behavior

JCenter is used.

**Comment by naveensingh** [comment]
Working on it, thanks!

**Comment by naveensingh** [comment]
Build success: https://gitlab.com/naveensinghcodes/fdroiddata/-/jobs/7888659956

It's not repro but it should be once I release a new update.

**Comment by linsui** [comment]
Thanks!
