### ISSUE TITLE
Photo compare function

### ISSUE THREAD

**Issue by OlegD-git** [FossifyOrg/Gallery#307]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I suggest adding a function to compare two photos, for example, as in Photo Compare programm.

### Why do you want this feature?

For example Photo Compare app https://github.com/sniederb/photocompare

**Comment by shockergit** [comment]
Try vesIC its in fdroid

**Comment by Saarsk** [comment]
Wouldn't mind such a feature if it's intuitive yet functionality-rich and efficient in use.

However, I think this is yet another thing that belongs in an extension to the main app(s).

But then again, I wouldn't want to fill up my phone with a bunch of app extension apps, so I'd prefer a single "app extension app" that lets you download the extra extensions you want. That way, there's one extra .apk and the main apps don't need internet access.

I imagine if it works like a library the other apps can tap into, it will still make sure the main apps can't connect to the web. It may even load these libraries into the main app's directory, although I don't know if it's possible to make it survive app updates if done like so.

Anyhow, extension app. :) Preferably a single one for all Fossify apps.

**Comment by OlegD-git** [comment]
I looked it up, this programme distorts the image when zooming in. There is also Photo compare on github. Maybe you can build Photo compare into Gallery - it's a very useful feature when developing photos from dng and when setting up Gcam.

28 сентября 2024 г. 05:29:39 GMT+03:00, shock ***@***.***> пишет:

**Comment by naveensingh** [comment]
Closing as out of scope for this app.
