### ISSUE TITLE
Some MP4 videos cannot be played (Source Error)

### ISSUE THREAD

**Issue by GuiSousa135** [FossifyOrg/Gallery#309]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0 (but this type of problem also happens in previous versions)

### Affected Android/Custom ROM version

Android 14 Lineage OS 21 (but it happens in all devices/roms that i tested)

### Affected device model

Samsung Galaxy S20 FE / Samsung Galaxy Tab S6 Lite (and others)

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Install any Gcam
2. Record a video
3. Try to play with Fossify Gallery
4. See the problem (Source Error)

### Expected behavior

The app should play the video normally, just like other apps.

### Actual behavior

When I record any video using Gcam on my Galaxy, the videos cannot be played by the Fossify Gallery, even though they are in MP4 format, it appears: Source Error. Other players or gallery apps can play normally. Videos recorded with OpenCamera can be played normally.

### Screenshots/Screen recordings

Example screenshot of the problem:

![Screenshot_20240927-120219_Gallery](https://github.com/user-attachments/assets/6f69ad00-ca5f-4092-b1dd-83301df163f8)

### Additional information

Example of a video I tried to play:

https://github.com/user-attachments/assets/097a4ca1-ea8c-48c2-a289-3086fba34ec9

**Comment by naveensingh** [comment]
I can reproduce this but only with corrupted/incomplete files.

**Comment by naveensingh** [comment]
I tried to play your file on my device and I got the following error: 

![image](https://github.com/user-attachments/assets/a4addddb-6a42-4057-9fbc-bb1d5eabfcdf)

It's probable that whatever video Gcam produced doesn't adhere to the MP4 specifications (thus malformed). For more info, see https://github.com/androidx/media/issues/1148.
