### ISSUE TITLE
[fr] export as PNG

### ISSUE THREAD

**Issue by throwaway242685** [FossifyOrg/Gallery#310]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

hi, it would be really useful to be able to export pictures as PNG after editing them.

### Why do you want this feature?

there's currently no way to export pictures in a lossless format.

**Comment by naveensingh** [comment]
Have you tried changing the extension to `png` in the export dialog?

**Comment by throwaway242685** [comment]
well, yes, but perhaps it would be better to be able to pick the default format to export like on [Snapseed](https://play.google.com/store/apps/details?id=com.niksoftware.snapseed):

<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/ef9c99bb-387d-46fa-99ec-a486dbe46eac" width=189 />

so it would automatically get saved as PNG?

**Comment by naveensingh** [comment]
> it would be better to be able to pick the default format to export

That's kind of planned. The extension input will be turned into a drop down menu with supported formats plus a custom option for those who need it (https://github.com/FossifyOrg/Gallery/issues/3#issuecomment-2357780855)

> so it would automatically get saved as PNG?

Yes, changing the extension also changes the format but only in the editor. When you are just renaming a file, changing the extension doesn't change the format.

**Comment by naveensingh** [comment]
> it would be better to be able to pick the default format to export


There's now an issue about this: https://github.com/FossifyOrg/Gallery/issues/701

**Comment by throwaway242685** [comment]
> The extension input will be turned into a drop down menu with supported formats (...)

this is a better approach than the one from Snapseed, btw.
