### ISSUE TITLE
Option to move top bar to bottom

### ISSUE THREAD

**Issue by Lppsoeht** [FossifyOrg/Gallery#319]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

A setting to move the to general bar(the one with search function) to bottom

### Why do you want this feature?

Having the bar at the bottom would facilitate using the search function.

**Comment by Aga-C** [comment]
Please raise issues regarding all apps in https://github.com/FossifyOrg/General-Discussion/issues.

**Comment by naveensingh** [comment]
I don't like this idea.

**Comment by naveensingh** [comment]
It is justified in the case of browser since all you do there is search. Anyway, I was just voicing my opinion (i.e. I'll be less inclined to implement something I don't like), you are free to raise this issue in the general repo, it might get implemented if enough people want it.

M3 bottom app bar: 
<img src="https://github.com/user-attachments/assets/98178f0a-10c1-4b58-b6a4-4838d01f058e" />

**Comment by naveensingh** [comment]
One of the things Fossify inherited from SimpleMobileTools is consistency. Something like 'option to move top bar to bottom' should either be added to all apps or none.
