### ISSUE TITLE
F-Droid Repo?

### ISSUE THREAD

**Issue by Syberkonda** [FossifyOrg/Gallery#32]
Will Fossify be on F-Droid?

**Comment by Aga-C** [comment]
See: https://gitlab.com/fdroid/rfp/-/issues/2612.

**Comment by Pentaphon** [comment]
It is already on Izzydroid repo: https://apt.izzysoft.de/fdroid/index/apk/org.fossify.gallery

**Comment by IzzySoft** [comment]
That said, it now also arrived at F-Droid itself, with the 2 next ones (Calendar, File Manager) already being processed there. What's the stance of Fossify concerning the apps in my repo? Usually I remove them once they arrived at F-Droid (given a decent overlap of 10..14 days). Would it be preferable for you to have them available in my repo as well? Thanks to reproducible builds, that would be not a problem apart from a little additional storage, so I'd be open to make an exception if you want it and find it helpful/useful.

@naveensingh @Aga-C

**Comment by Aga-C** [comment]
@IzzySoft If it's not a problem for you, IMO it's better to have more mirrors.

@naveensingh What do you think?

**Comment by naveensingh** [comment]
@IzzySoft Yes please, I agree with @Aga-C on this.

But if keeping them there requires extra work from you, please remove them.

**Comment by IzzySoft** [comment]
Cascade: Noted, will do.

Auto-Pull of Fastlane: Yes. Just if the "formatting standard" changes I need to adjust here (so please let me know once it's there and ideally *before* you tag the release following the change).

Other than F-Droid, my repo has some more flexibility built in there (I also can set the "Fastlane root" for each app specifically to support non-standard locations). For fulldesc, it e.g. offers 3 different modes: 1) consider input being Markdown, 2) take input as-is (usually HTML), 3) replace all line-breaks with `<br>` (basically what F-Droid does, but that's the least favorited way). Currently, I've set it for the latter as the other two methods would not work; once you've switched to HTML I'd switch it to either Markdown or as-is.

In all 3 variants, my updater would convert it to HTML, [sanitize it](https://gitlab.com/IzzyOnDroid/repo/-/blob/master/lib/upstream.class.php?ref_type=heads#L957) (e.g. removing any `<script>` and other evil stuff) and strip all not-needed line breaks, so fdroidserver has none left to insert unwanted `<br>`s into it. It will also replace any headings (H1..H6) it finds to not break page structures (h1..h3 will become font-weight bold + large, h4..h6 just bold).

Example: Just expand the details above :wink: Using of DL was just a try, you can use UL as well (`style=` is basically supported if you want to replace bullet points by icons – though I think those icons are more fancy than really useful :see_no_evil:)

**Comment by naveensingh** [comment]
@IzzySoft Understood, thanks! I'll let you know when I update the description format.
