### ISSUE TITLE
"Move to" missing from ⋮ menu when viewing a single image

### ISSUE THREAD

**Issue by Robio** [FossifyOrg/Gallery#324]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Gallery/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.1

### Affected Android/Custom ROM version

Android 11

### Affected device model

Moto G Power 2020

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open an individual image
2. ⋮  more menu
RESULT: "Move to" option is missing

3. Return to gallery view
4. Long-tap on an image
5. ⋮  more menu
RESULT: "Move to" is present

Checked against Simple Gallery 6.28.1 to make sure this wasn't a carry-over bug.
It's not.

### Expected behavior

"Move to" would be present in ⋮ menu for individual images.

### Actual behavior

"Move to" is note present.

### Screenshots/Screen recordings

<img alt="FOSSIFY GALLERY 2024-10-04 BUG - no  move to  01" src="https://github.com/user-attachments/assets/2829fc19-3008-47e4-a278-fa6ff173031e" width=187 />
<img alt="FOSSIFY GALLERY 2024-10-04 BUG - no  move to  02" src="https://github.com/user-attachments/assets/fecdb0a1-a063-4758-aafe-e5d3fd95523e" width=187 />

**Comment by Aga-C** [comment]
![obraz](https://github.com/user-attachments/assets/1b09cc98-1c3b-4f96-ae83-ba2c6116f32f)

**Comment by Robio** [comment]
> ![obraz](https://private-user-images.githubusercontent.com/85929121/373849645-1b09cc98-1c3b-4f96-ae83-ba2c6116f32f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDkwOTAsIm5iZiI6MTcyOTMwODc5MCwicGF0aCI6Ii84NTkyOTEyMS8zNzM4NDk2NDUtMWIwOWNjOTgtMWMzYi00Zjk2LWFlODMtYmEyYzYxMTZmMzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAzMzMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZjMxODBhNDgxNThiNThhYTkyMDZkMTNlYTE0ZGY5MGUxOGEwYTM2N2VlMGU5Y2MxNTc1OWZjNzczOTBmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XFmHmXCjmicfTHPWotHWjird9dLp5ip9pU-ZVXEYM-A)

*head-desk*
I forgot I'd done that. Wow. What a dope!
In my defense, I made that change about a month ago, and it was the first toolbar change I'd made for _years_ (across Fossify Gallery and Simple Gallery). Still, big dummy here.

/CLOSES TICKET
/HANGS HEAD IN SHAME

**Comment by Robio** [comment]
User error. See above.
