### ISSUE TITLE
Hi resolution images are blurry when zoomed in. 

### ISSUE THREAD

**Issue by tryrebooting** [FossifyOrg/Gallery#33]
I am seeing an issue with Zoom. I have images in Fossify Gallery taken with a Fuji x100v at 6240 x 4160 (26.0MP) and they are blurry when zoomed in. See the attached image... Fossify Gallery on left, Aves Libre n right. Both at max zoom. The Fossify Gallery will not zoom all the way in. 

All settings under Deep Zoomable Images are enabled. 

This issue is not present on Simple Mobile Gallery on the same device. 

[Fossify Gallery Zoom Issue ](https://i.imgur.com/yOoqD7N.jpg)

**Comment by Aga-C** [comment]
Please adjust your bug report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Aga-C** [comment]
@naveensingh I quickly investigated it and found out that zoom is done using a library that's Tibor's fork: `com.github.tibbi:subsampling-scale-image-view`. He probably protected it to not be used outside SMT, looking at lines like https://github.com/tibbi/subsampling-scale-image-view/blob/80efdaa570d8c40cd84be4c82f6a7438fe32c465/library/src/main/kotlin/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.kt#L184.

We'd either should use the original version of the library, but I haven't checked what changes Tibor did, or fork Tibor's fork and remove protections.

**Comment by inson1** [comment]
@tryrebooting there is option for highest possibe quality in deep zoomable images, did you try it?

**Comment by Aga-C** [comment]
@inson1 It doesn't matter, I've checked it. It's a different issue (see my comment above).

**Comment by naveensingh** [comment]
@Aga-C thanks for the quick investigation. 

I forgot to update those libs. I just transferred the forked library to this organization. While I don't have a detailed list, there were some bug fixes in the SMT fork so we'll continue using it.

In the case of the subsampling image view, I think a fork was created because the upstream wasn't accepting PRs at that time. Maybe we'll later merge any upstream changes with our fork. For now, I'm going to focus on fixing this.

**Comment by naveensingh** [comment]
https://github.com/FossifyOrg/Gallery/releases/tag/1.0.2 should fix this.

**Comment by tryrebooting** [comment]
Can confirm as working as expected now. Thank you.

**Comment by CTappe** [comment]
With the App version 1.1.3 and Android 14, I am experiencing the bug described above again. If I take photos with my camera, the raw dng format is displayed blurry while the standard gallery displays it in the normal quality. If I take jpg files, they look fine. Also, I can not zoom in much on the dng file as I can on the jpg file. I have deep zoomable images activated.

On the screenshot you see the dng file with the standard gallery and with  Fossify Gallery. If I convert the dng file to a jpg file, it is displayed correctly and I can zoom in much more.

![Screenshot_2024-06-03-19-10-50-187_org fossify gallery](https://github.com/FossifyOrg/Gallery/assets/171605614/f9d3e061-3cf3-4f25-97c1-ec954c2b1398)

**Comment by Aga-C** [comment]
@CTappe Could you report it separately as a new bug? It seems to be an entirely different issue related to RAW files handling.

**Comment by CTappe** [comment]
@Aga-C I reported a new bug, see #239
