### ISSUE TITLE
Quick filter for gallery view

### ISSUE THREAD

**Issue by parrenin** [FossifyOrg/Gallery#336]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I like the gallery view because there are dates which give you a timeline.
However, all sources are mixed together (camera, WhatsApp, etc.) which can be annoying.
Therefore, I would like a quick filter to choose the sources in this view.

### Why do you want this feature?

To use the gallery view with one particular source.

**Comment by Aga-C** [comment]
How would it be different from the current folder view?

**Comment by parrenin** [comment]
It would be different because 1) you can choose to display several folders and 2) you have the dates displayed.

**Comment by Aga-C** [comment]
If so, it's already requested: https://github.com/FossifyOrg/Gallery/issues/132.
