### ISSUE TITLE
Add option to change playback speed 

### ISSUE THREAD

**Issue by Gamer750** [FossifyOrg/Gallery#34]
Add option to change playback speed of video. Please also add default playback speed

**Comment by Aga-C** [comment]
Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by Aga-C** [comment]
@Ehab-d Thanks for reporting it once again!
