### ISSUE TITLE
The slideshow doesn't work

### ISSUE THREAD

**Issue by stefknecht** [FossifyOrg/Gallery#35]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
The slideshow doesn't work. Only the first image of a folder is shown. Changing the slideshow options in the slideshow-dialogue doesn't change anything.

**To Reproduce**
1. Select a folder with more than 1 image 
2. Go to the 'Main menue'
3. Click on '...' (the three points)
4. Click on 'Slideshow' 
5. Setup the slideshow options
6. Click on 'OK'
 7. See error: Only the first image of a folder is shown. No slideshow is active. There's no switch to another image  

**Describe the bug**
The slideshow doesn't work. Only the first image of a folder is shown. Changing the slideshow options in the slideshow-dialogue doesn't change anything.

**Expected behavior**
With the slideshow an automatically switch to images in a selected folder should be made. The chosen options in the slideshow-dialogue, that is shown when 'Slideshow' is clicked in the main menu, should be applied.

**Screenshots**

**Device info (please complete the following 
information):**
 - Model: Pixel Pro 7
 - OS: Android 14
 - Version 1.02

**Additional context**

**Comment by blackfyre** [comment]
Can confirm that this is still a problem!

**Comment by Aga-C** [comment]
I got an update to Android 14 (stock) on my OnePlus 9 Pro and there's no problem with slideshow. Everything works as it was working on Android 13. I even reinstalled the app and still there wasn't any problem. 

I have a suspicion that it may be an OS-specific issue, so I label it as device/software specific.

**Comment by CortJstr** [comment]
I'll pitch in that it's also not working on my phone. I see the same behavior described above where it just stays on the current image indefinitely.

- OS: Android 14 w/ February 2024 security update
- Device: Pixel 8 Pro
- App version: 1.1.1

**Comment by blackfyre** [comment]
@Aga-C I'm happy to test builds, but since I'm not familiar with the Android SDK I can't offer more 😢

**Comment by naveensingh** [comment]
Should be fixed in the next update. I tested on my phone with stock Android 14 and a tablet with Android 14 GSI.

**Comment by blackfyre** [comment]
Can confirm, it's working now!
