### ISSUE TITLE
Slide along the image side to adjust light

### ISSUE THREAD

**Issue by anderslundx** [FossifyOrg/Gallery#360]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I miss a feature from simple gallery, that allowed to drag vertically along the image/screen edge to adjust light.

### Why do you want this feature?

This feature makes my life better, because adjusting light makes many images look better and clearer.

**Comment by Aga-C** [comment]
We haven't removed this feature.

**Comment by anderslundx** [comment]
This feature is really cool. It adjusts brightness, described in this file in simple gallery: https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/app/src/main/kotlin/com/simplemobiletools/gallery/pro/views/MediaSideScroll.kt

**Comment by Aga-C** [comment]
...and it's still there: https://github.com/FossifyOrg/Gallery/blob/master/app/src/main/kotlin/org/fossify/gallery/views/MediaSideScroll.kt

**Comment by naveensingh** [comment]
**Note:** You have to enable it in app settings.

**Comment by anderslundx** [comment]
Hi,

It doesn't work here. I move my finger exactly like I do using simple gallery - 
vertically on left edge of screen while viewing a photo - but it doesn't do 
anything in the fossify version. Does it work for you?

mandag den 18. november 2024 20.07.47 Centraleuropæisk normaltid skrev 
Agnieszka C:
> ...and it's still there:
> https://github.com/FossifyOrg/Gallery/blob/master/app/src/main/kotlin/org/f
> ossify/gallery/views/MediaSideScroll.kt

**Comment by anderslundx** [comment]
There we are, thanks a lot :)

mandag den 18. november 2024 20.10.55 Centraleuropæisk normaltid skrev Naveen 
Singh:
> **Note:** You have to enable it in app settings.

**Comment by D15A-Jai-61** [comment]
How do I disable this feature for all media ? The settings page of the Fossify gallery only shows a toggle to disable the brightness gesture for photos, but not for videos or for all media together.

**Comment by naveensingh** [comment]
@D15A-Jai-61 For videos, it's under the videos section. 

Fossify Gallery ➜ Settings ➜ Scroll to videos section ➜ Allow controlling video volume and brightness with vertical gestures

**Comment by nakic** [comment]
Does anyone other than me find the current behaviour of brightness adjustment by side-swiping finnicky? For a few examples:

* if I take it down to 0% or up to 100%, while still keeping my finger pressed on the screen, I can't go back to e.g. 50% brightness: I have to stop the swipe and then swipe anew to adjust
* it goes up to 100% in a few mm of swipe distance: I would expect it to work over 3-4 cm: small enough to comfortable reach, long enough to allow fine adjustment
* sometimes (not clear when) when I start swiping, it will simply not affect brightness at all

**Comment by D15A-Jai-61** [comment]
@naveensingh thanks, your response helped.

> @D15A-Jai-61 For videos, it's under the videos section. 
> 
> Fossify Gallery ➜ Settings ➜ Scroll to videos section ➜ Allow controlling video volume and brightness with vertical gestures

**Comment by D15A-Jai-61** [comment]
@nakic I personally can't relate because I don't use it, as I tend to touch and rub the screen during use to clean the dirt and grease that gets on it, so the feature gets annoying and I just turn it off.

> Does anyone other than me find the current behaviour of brightness adjustment by side-swiping finnicky? For a few examples:
> 
> * if I take it down to 0% or up to 100%, while still keeping my finger pressed on the screen, I can't go back to e.g. 50% brightness: I have to stop the swipe and then swipe anew to adjust
> * it goes up to 100% in a few mm of swipe distance: I would expect it to work over 3-4 cm: small enough to comfortable reach, long enough to allow fine adjustment
> * sometimes (not clear when) when I start swiping, it will simply not affect brightness at all
