### ISSUE TITLE
Could a simple standalone image editor with `unrestrained Crop` Tool be possible?

### ISSUE THREAD

**Issue by rajibando** [FossifyOrg/Gallery#371]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Gallery/issues) or [closed](https://github.com/FossifyOrg/Gallery/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Gallery/discussions) or [closed](https://github.com/FossifyOrg/Gallery/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Gallery/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

May please this F-Droid Discussion, [Is there an image perspective correction tool in F-Droid Repo?](https://forum.f-droid.org/t/is-there-an-image-perspective-correction-tool-in-f-droid-repo/29530), and the discussion #370 here, in `FossifyOrg/Gallery` be perused.
Having been using GIMP for the last 14 years, I am sure that a shredded GIMP would be more than sufficient for empowering all users of F-Droid for simple touch up of photos, particularly, for correcting the  distortions arising from the lens of smartphones or the way the phone is held for clicking photos.
Hope to find a shredded GIMP like app in F-Droid soon, aware that you are the one team best placed to have the last mile gap bridged.
[GIMP source code is FOSS](https://developer.gimp.org/core/setup/build/#download-the-source-code). So for programmers of your capability a shredded porting shouldn't be difficult at all.
At least, had I been a professional programmer, I would definitely have tried.
There is a demand for such an app in the FOSS universe, I can vouch.

Therefore the request is posted on the subject line itself:

Unrestrained Crop, where each of the four vertices could be moved independently from the rest.

### Why do you want this feature?

There isn't another app available on the FOSS F-Droid universe, while for programmers of your capability it would have been easy to bridge.

### Additional information

GIMP being an Open Source Software under the GNU license, it could be altered and shredded and reused for other users.

**Comment by Aga-C** [comment]
>(1) Unrestrained Crop, where each of the four vertices could be moved independently from the rest.
>(2) Perspective, lens distortion, etc., correction tools

These are multiple requests, yet you've checked:

>This issue contains only one feature request.

**Comment by Aga-C** [comment]
I've asked to have one request about unrestrained crop, which performs perspective correction. It doesn't make any sense to split it. I wrote about "multiple requests" because you've originally written about fixing lens distortion and other tools. I'm closing this issue and the one about perspective correction in favor of #374.

**Comment by rajibando** [comment]
> I've asked to have one request about unrestrained crop, which performs perspective correction. It doesn't make any sense to split it. 
Dear Mr. Agni,
Unrestrained Crop isn't equivalent to Perspective Correction. The first is planer, while the second is spherical/cylindrical/Conical.
So had I been in your place, I would have let the three together and add the two independent features together, and the third one to have the two tools in one app.
