### ISSUE TITLE
Thumbnail spacing

### ISSUE THREAD

**Issue by svendsvin** [FossifyOrg/Gallery#39]
I tried to reproduce the problem but can't. The spacing just stay the same. I played around with the settings and at first I could change the thumpnail space setting, but then out of nowhere it went back to the original (think it's 1x). I tried to set it to everything up to 64x, but nothing change.

**Comment by Aga-C** [comment]
Please adjust your bug report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/bug_report.md).
