### ISSUE TITLE
[Migration] Compose-first approach (all new layouts and long-term migration)

### ISSUE THREAD

**Issue by machiav3lli** [FossifyOrg/Gallery#41]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**

Current code base is 100% Kotlin, but still uses the kinda-legacy Android layout views system.

**Describe the solution you'd like**

Using Jetpack Compose would ease working with layout options (e.g. Adapters/Recyclers, views designs #13) and allows dropping the use of some dependencies (e.g. #36). 

Migrating the whole code at once is a relatively big project with a lot of sub-tasks (started to get the hang of it, after doing this for 3 projects). That's why it'd make sense at first to only (re)implement anything in Compose when it's being added or touched/modified.

If someone is willing to take on such task, I'm gladly available for discussion.

**Comment by Aga-C** [comment]
@machiav3lli Can you raise this in [General Discussions](https://github.com/FossifyOrg/General-Discussion/issues)? It affects all apps, not just Gallery, so it's a better place for this issue.

**Comment by machiav3lli** [comment]
FossifyOrg/General-Discussion#63 Done, should this be closed?

**Comment by inson1** [comment]
@machiav3lli if you do add it to https://github.com/FossifyOrg/General-Discussion/issues please add the list with all apps, so we would know what is done and what isnt
