### ISSUE TITLE
A white splash screen for light themes

### ISSUE THREAD

**Issue by pudup** [FossifyOrg/Gallery#49]
This would apply to all the fossify apps that are forks of SMT. Posting it here since it's the only one on f-droid at the moment.

The launch splash screen is black regardless of theme. Light themed apps should have a white splash screen.

**Comment by Aga-C** [comment]
Please raise issues regarding all projects in https://github.com/FossifyOrg/General-Discussion/issues.

**Comment by naveensingh** [comment]
@pudup yes, I noticed that too but please raise this in general discussion.
