### ISSUE TITLE
We have to remove the paid editor sdk

### ISSUE THREAD

**Issue by inson1** [FossifyOrg/Gallery#5]
"Per the GNU GPL, proprietary SDKs cannot be combined with GPL code in the same project. Either way, this proprietary library will have to be removed so that the project stops violating the GPL."

**Comment by Aga-C** [comment]
I'm closing this, because after quick research I found it's not true: https://www.gnu.org/licenses/gpl-faq.html.en#FSWithNFLibs. If you want to discuss using proprietary editor in the future, please use discussions.

**Comment by inson1** [comment]
@Aga-C it was in discussions + naveensingh answered it, so that is why I didnt do any research  :) I changed the name + it needs to by removed anyway, because isnt going to be any pro version and the sdk costs money - easiest would be to remove it :)
May you reopen it?

https://github.com/orgs/FossifyOrg/discussions/9#discussioncomment-7756115
Plus https://github.com/orgs/FossifyOrg/discussions/9#discussioncomment-7793145

**Comment by Aga-C** [comment]
@inson1 I think it's more relevant to discussions (Ideas category), because in issues it's better to keep things that can be taken by potential contributors to fix/develop 🙂 This topic is rather up to decide what to do.

**Comment by inson1** [comment]
@Aga-C so please create discussion from it, you can do it right? :)

tbh to me it feels more like already decided thing, but why not
