### ISSUE TITLE
No tools on Lenevo tablet

### ISSUE THREAD

**Issue by lianergoist** [FossifyOrg/Gallery#50]
After my tablet had an automatic upgrade from android 11 to android 13, the tools in the bottom of the screen is missing. I use ver. 1.1.0 on both my tablet and phone (android 9), and the tools/icons are still there on the phone. See screenshots.

![Screenshot_20231124-192325](https://github.com/FossifyOrg/Gallery/assets/6023573/94b3af4e-85ff-41fe-b61e-91d941184613)
![Screenshot_20231124-193042](https://github.com/FossifyOrg/Gallery/assets/6023573/12df65d1-a913-4919-95ff-25e4f6301b44)

(Copy of this bug: https://github.com/SimpleMobileTools/Simple-Gallery/issues/3045)

**Comment by Aga-C** [comment]
Please adjust your bug report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Aga-C** [comment]
@lianergoist I am closing this issue because it didn't comply with old issue template, wasn't fixed and some time ago we've moved to issue forms. If you still want this issue to be open, please raise a new issue with a properly filled form.

**Comment by inson1** [comment]
new issue with fixed tamplate  https://github.com/FossifyOrg/Gallery/issues/141
