### ISSUE TITLE
 Rotating Device Brings You Back To First File

### ISSUE THREAD

**Issue by seniorm0ment** [FossifyOrg/Gallery#51]
**Checklist**
 - [X ] I can reproduce the bug with the latest version. 
 - [ X] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [X ]  I have read the FAQ and my problem isn't listed.
 - [ X]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [X ]  This issue contains only one bug.
 - [ X]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
When scrolling through videos, and then rotate the device, it resets back to the first clicked video.

**To Reproduce**
1. Go to video, click it
2. Start scrolling through videos and photos
3. Rotate the device
4. See it flicker then bring you back to the first file

**Expected behavior**
Expect it to rotate screen and stay on current file

**Device info (please complete the following information):**
 - Model: Pixel 8 Pro
 - OS: Android 14 GrapheneOS
 - Version: [2023123100](https://grapheneos.org/releases#2023123100)

**Comment by Aga-C** [comment]
I can't reproduce it. Can you provide more details?

- Can you tell what settings do you have in sections: Videos, Scrolling, Fullscreen media? If you can, screenshots would be the best.
- In the first step, do you mean clicking on a video in a grid view with all videos, or you're already in the full-screen video and you're clicking it?
- How are you rotating? Do you have auto-rotating in OS? Or do you have it blocked in OS, and you're only relying on rotating via app setting?

BTW. Version in device info is a version of the app, not your exact OS version.

**Comment by seniorm0ment** [comment]
I believe this person is having the same issue: https://github.com/SimpleMobileTools/Simple-Gallery/issues/3051
I went to go make the same issue there then realized the project was forked. 

- Version 1.1.0 from F-Droid
- When in grid mode, you click a file, then start scrolling, rotate anytime. It also does it with Photos I just noticed too. Not strictly videos.

>Videos

Checked: Play videos auto, loop videos, allow controlling with gestures

>Scrolling

Checked: Enable pull to refresh

> Fullscreen Media

Checked: Auto hide system ui, allow closing fullscreen view with down gesture, show notch if available,rotate media by system setting

**Comment by Aga-C** [comment]
Just to be sure:
1. The issue you gave from SMT says about selecting images. By clicking image, you mean long pressing it to enter selection mode or just a single quick tap that brings you to full-screen display?
2. Is it also the same as https://github.com/SimpleMobileTools/Simple-Gallery/issues/2822?

**Comment by seniorm0ment** [comment]
> Just to be sure:
> 
>     1. The issue you gave from SMT says about selecting images. By clicking image, you mean long pressing it to enter selection mode or just a single quick tap that brings you to full-screen display?
> 
>     2. Is it also the same as [Screen Rotate issue/bug SimpleMobileTools/Simple-Gallery#2822](https://github.com/SimpleMobileTools/Simple-Gallery/issues/2822)?

Both issues seem to be the same yes.
And no, not when holding down.

When you are in the grid view, you single tap an image or video to view it full screen. Then swipe left or right, then turn the device. It rotates, then hops back to that first file no matter how many files you swiped through

**Comment by seniorm0ment** [comment]
To be clear though, this issue was present before the fork. So it's nothing you have changed.
I do appreciate the efforts with the fork btw.

**Comment by Aga-C** [comment]
Thanks for clarifying! I still can't reproduce the issue (I have a non-rooted OnePlus), so I suppose it's device or OS specific. Probably also related to #54.

**Comment by replica9000** [comment]
I have this issue as well on my OnePlus 12.  @manigmaX (on SMT Git) pointed out that it happens with a high DPI.  I normally run my phone at 520 (set in Developer Settings).  The issue goes away if I keep the DPI under 478.

**Comment by naveensingh** [comment]
@seniorm0ment @replica9000 here's an APK with a potential fix: https://github.com/FossifyOrg/Gallery/pull/160#issuecomment-1984760344

Let me know if it works, thanks!

**Comment by replica9000** [comment]
@naveensingh The apk you provided fixes the issue for me, thank you!

My OnePlus is running A14, but the issue was the same on my older OnePlus running A13 as well.

**Comment by naveensingh** [comment]
@replica9000 I guess I'll accept my PR then :)
