### ISSUE TITLE
Add support to AVIF

### ISSUE THREAD

**Issue by jlHertel** [FossifyOrg/Gallery#56]
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
I have a very big library of images (100 GB+) and decided to convert everything to AVIF to save space. Unfortunately the app is unable to display them.
This previously was reported [here][1], and a solution is also suggested, but it never got picked up.

**Describe the solution you'd like**
All AVIF images are supported, even in old devices.

**Describe alternatives you've considered**
WebP might be an alternative, although it has less compression.

**Additional context**
It seems AVIF is partially supported already, as some images with smaller resolutions show fine.

[1]: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2496#issuecomment-1809801476

**Comment by Vinfall** [comment]
> WebP might be an alternative, although it has less compression.

I think WebP is well supported already, even in Simple Gallery.

***

Besides that, as the example in [previous discussion](https://github.com/SimpleMobileTools/Simple-Gallery/issues/2496#issue-1257173467) is now 404, you can use [avif-sample-images](https://github.com/link-u/avif-sample-images) as an alternative test sample, esp. those with odd width or weight. Other gallery apps I use can display normal ones but not those with odd resolution.
