### ISSUE TITLE
Picture rotate

### ISSUE THREAD

**Issue by DeadSecTr** [FossifyOrg/Gallery#63]
Picture rotate doesnt work at the first time after choose a Photo,must close the photo than open again than rotate works.

(Android 13 Moto g42)

**Comment by Aga-C** [comment]
Please adjust your bug report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by DeadSecTr** [comment]
Witch part do you dont understand?

**Comment by naveensingh** [comment]
@DeadSecTr we understand your problem but please update your report as per the requested issue template.
