### ISSUE TITLE
Add swipe to archive/delete for the SMS application

### ISSUE THREAD

**Issue by longestmt** [FossifyOrg/Gallery#65]
**Checklist**
 - [ x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x ]  I have read the FAQ and my problem isn't listed.
 - [x ]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x ]  This issue contains only one feature request.
 - [x ]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
The simple sms application requires a long press to select and fumbling through the menu to archive/delete the ability to swipe left or right is more intuitive.

**Describe the solution you'd like**
It would be great to have the left or right swipes configurable to either archive or delete.

**Describe alternatives you've considered**

**Additional context**

**Comment by inson1** [comment]
I would only add it as add on option, I dont want it as default

**Comment by ikanakova** [comment]
> > I would only add it as add on option, I dont want it as default
> 
> @inson1 may I ask why you need a switch? If you don't like the feature, just don't swipe?

I think because someone could accidentally swipe and delete the message.

My opinion is that instead of a toggle, there should be a gesture setting like in gmail, where the user can choose under Swipe Actions what is done by swiping right and left, both with a No Action option.

**Comment by naveensingh** [comment]
Usually, the swipe gesture implementation isn't that sensitive + there will be a snackbar with a **UNDO** text for a few seconds.

**Comment by ikanakova** [comment]
But would it be optional what each swipe action does (delete / archive)? Because everyone is used to something different because [there is no consensus on what swipe right and left will do](https://ux.stackexchange.com/questions/96986/what-is-the-default-or-accepted-convention-for-swipe-gestures-on-mobile-applicat).

**Comment by naveensingh** [comment]
Yes, it should be customizable. On another note, @longestmt why is this issue [here](https://github.com/FossifyOrg/Gallery/issues/65?)? 

It should be in the [SMS-Messenger repo](https://github.com/FossifyOrg/SMS-Messenger/issues).

**Comment by inson1** [comment]
@longestmt close it here :)
