### ISSUE TITLE
Visibility of video duration in thumbnail

### ISSUE THREAD

**Issue by jcperil** [FossifyOrg/Gallery#7]
**Checklist**
- [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
- [x]  I have read the FAQ and my problem isn't listed.
- [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [x]  This issue contains only one feature request.
- [ ]  I have read and understood the [contribution guidelines.](https://github.com/FossifyX/General-Discussion?tab=readme-ov-file#contribution-rules-for-developers)

**Is your feature request related to a problem? Please describe.**
The video duration shown in thumbnails can sometimes be hard to read depending on the thumbnail colors.

**Describe the solution you'd like**
I would recommend something like YouTube thumbnails where they put the video duration in a semi-transparent black box for better visibility.
![thumbnail](https://user-images.githubusercontent.com/89805719/212532731-a0a04077-8648-4674-8d3d-2e2183ca2a31.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by Aga-C** [comment]
Top right is also already taken. Favorites' star icon is displayed there.

**Comment by jcperil** [comment]
As you see it fit.

**Comment by gmasil** [comment]
Something like this?

![gallery-video-duration-background-example](https://github.com/FossifyOrg/Gallery/assets/54176035/034eacd6-eb4b-4063-89c4-6bb17ac73873)

**Comment by jcperil** [comment]
@gmasil Yes. How does it look when applied on a white-ish thumbnail? Maybe a little bit darker like YouTube.

**Comment by gmasil** [comment]
I took a transparency from the design palette, I can theoretically use any color there is, but I'd rather hear the opinion of @naveensingh and @Aga-C regarding the design. Please let me know what you think, in case you agree I have a PR ready to go.

**Comment by Aga-C** [comment]
@gmasil On this screenshot, it looks good to me 👍

**Comment by naveensingh** [comment]
Why not merge both of the elements? A single rectangular background with the play icon followed by the video duration. It'll look better. I think Samsung's gallery has it like that.

You can experiment with the corner radius and the height to see what looks good or I'll do it before merging the PR.

Also, @gmasil please considering using `<img src="github_image_url_here" width=264 />` for screenshots.

**Comment by gmasil** [comment]
Ready to merge if you agree. Add comments to the PR if you want to propose changes, I'll implement them to your likings.
