### ISSUE TITLE
feature request: empty recycle bin from three dot menu from the albums/main view pls 🙏

### ISSUE THREAD

**Issue by valtoree** [FossifyOrg/Gallery#76]
hi
love your app,
can we please get the below integrated?

**Checklist**
 - [ x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [ x]  I have read the FAQ and my problem isn't listed.
 - [ x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [ x]  This issue contains only one feature request.
 - [x ]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
currently I have to go into the recycle bin folder, then hit the three dot menu to empty recycle bin.
but I would rather just empty the bin from the albums/main view.

**Describe the solution you'd like**
empty recycle bin from three dot menu from the albums/main view pls

**Describe alternatives you've considered**
an empty rubbish icon on home screen

**Additional context**
none

regards

**Comment by Aga-C** [comment]
Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by valtoree** [comment]
> Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

ok done, sorry

**Comment by naveensingh** [comment]
@valtoree 

> currently I have to go into the recycle bin folder, then hit the three dot menu to empty recycle bin.

Not true. You can empty the recycle bin from the main page:
 - Long press the recycle bin folder on the main view
 - Tap on the delete button
 - Tap "OK" on the empty recycle bin dialog.

So basically the same process as deleting a folder. There is also a duplicate option:
 - Long press the recycle bin folder on the main view
 - Tap on the three-dot button
 - Tap on "Empty the recycle bin" option
 - Tap "OK" on the empty recycle bin dialog.

I'm closing this as this is more or less already implemented. We'll get rid of the duplicated option.

**Comment by valtoree** [comment]
Thank you for reply much appreciated.
 I guess I forgot to mention that my recycle bin folder is the last folder as per my preference. So I'd have to scroll all the way down to do your solution. Are we able to implement the feature where I dont have find the recycle bin folder please?
Thanks for all your hard work.
Regards
