### ISSUE TITLE
Request: text tool for image editor - doodle not enough

### ISSUE THREAD

**Issue by G-D-B-9-9** [FossifyOrg/Gallery#78]
Request: text tool for image editor - doodle not enough. Perhaps similar to that of Google Photos app? Simple.

Awesome app you have! Text tool is simple yet big basic editing feature.

**Comment by Aga-C** [comment]
Please adjust your feature request report to the [issue template](https://raw.githubusercontent.com/FossifyOrg/Voice-Recorder/master/.github/ISSUE_TEMPLATE/feature_request.md).

**Comment by Aga-C** [comment]
Reported by someone else with the properly filled template: https://github.com/FossifyOrg/Gallery/issues/97.
