### ISSUE TITLE
Geotagging/Map Support

### ISSUE THREAD

**Issue by seniorm0ment** [FossifyOrg/Gallery#83]
**Checklist**
 - [ X] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [ X]  I have read the FAQ and my problem isn't listed.
 - [ X]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [ X]  This issue contains only one feature request.
 - [ X]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
Can't find by location

**Describe the solution you'd like**
Similar to how Apple Photos works, for photos that have geotag information, show them on a map
See: https://support.apple.com/guide/iphone/view-photos-and-videos-iph3d267610/17.0/ios/17.0#iph3d5d1d7dd

Also ability to search by location and such

**Comment by inson1** [comment]
I think it would be great have map of the world and see different albums of photos by locations and with search etc.,
it would be third view mode,
we could use openstreetmap for that, 
it would be great functionality, but hard to implement I guess
plus it would be also great for findind geotag photos to delete the geotag info

question is where it should it be? maybe in menu?

**Comment by seniorm0ment** [comment]
Yes that is sorta how Apple Maps works. You can open a full map view and it has the photos layed out across the map where they are geotagged.
I believe Google Photos has a similar feature.

As for the button, we can simply place a map button somewhere in the top right that opens the full map. 

Then when on a specific photo, you could slide up and see the photo information and a preview of the map area where the photo was taken. Again see the link I posted at the bottom of my issue.

**Comment by inson1** [comment]
@seniorm0ment Google photos has map in photo info, not map view

right now the top right is full of buttons

**Comment by naveensingh** [comment]
I also want to replace Google Photos on my phone but Fossify apps operate without any internet access and that means we might miss out on cool features like this. Internet access will only be added if it is required by some core functionality.

Integrating Google's Maps SDK which probably isn't open source is another issue.

**Comment by seniorm0ment** [comment]
Could we not maybe have some sort of plugin feature? Where users can _choose_ to enable? Or a second fork with internet?
I know it may require more development power but it would allow for extra stuff like NAS connections and such as well.

Also for maps we could use Openstreetmap

**Comment by inson1** [comment]
@naveensingh I also dont get it why we need internet access for offline maps.

**Comment by naveensingh** [comment]
>I also dont get it why we need internet access for offline maps.
> Realistically I fail to see why this would require internet access, seeing maps can be viewed offline?

I haven't worked with maps recently so I have no idea if there were any advancements. Does anyone know how much storage space you need to store a relatively low-res (1km/pixel?) vector map of the whole world? 500MB? 5GB?

I don't think it would be under 30MB and I'm not going to bump the app size by 30MB+ for anything that isn't a core feature of the app.

> Could we not maybe have some sort of plugin feature? Where users can choose to enable? Or a second fork with internet?
I know it may require more development power but it would allow for extra stuff like NAS connections and such as well.

We could and that version would probably become more popular and I actually have thought about this before. Launching two flavors where one is simple and the other is loaded with all the cool doodads that are possible with access to the internet but we don't have the time or resources to maintain current apps, let alone two flavors.

**Comment by seniorm0ment** [comment]
This may be a really stupid question as someone on GrapheneOS, but can you not deny internet permissions on stock Android?

I understand the concept behind wanting an app to not touch the internet be design, however I know on my device I can flat out deny internet permissions to an app.
Maybe this is a GrapheneOS feature, however I thought this was a part of Android's "privacy features" they've implemented over the past 2 major updates? If so, why not simply incorporate internet permissions, and just have them disabled by default and users who don't want it don't have to give it that permission?

I don't mean to be argumentive or anything, I am genuinely curious as this is something I've wondered for a bit.

**Comment by naveensingh** [comment]
> can you not deny internet permissions on stock Android?

I don't think so. At least on my device running stock AOSP ROM, I haven't found any way to disable internet permission for an app. You can disable background data usage but that is all you can do.

Android docs: 

> Normal permissions allow access to data and actions that extend beyond your app's sandbox but present very little risk to the user's privacy and the operation of other apps.

I don't know how the [INTERNET](https://developer.android.com/reference/android/Manifest.permission#INTERNET) permission is considered a "normal" permission. The way I see it, it is the most dangerous permission an app can have. 

They should have moved the INTERNET permission from `normal` set to `runtime` set instead of introducing that annoying POST_NOTIFICATIONS `runtime` permission.

(I'm not really an anti-Google person, I use many of Google's products but I know why Google doesn't want users to worry about the INTERNET permission and I don't like Google for that)

**Comment by seniorm0ment** [comment]
Hm ok interesting, so likely a GrapheneOS feature. Good to know.
It is very nice though for your knowledge, in case you were not aware upon an app installation it prompts for network access toggle before install.
Then after install you can adjust it like all other permissions.

**Comment by yusufsunetci** [comment]
An open source program called Aves can be reviewed for this. The codes can be received there at the moment. It's a very nice feature.

**Comment by inson1** [comment]
If size is concern we dont have to add big zoom, map in #125 could be enough, but yea we need more informations for this, so if someone wants this feature please go and try to find more about zoom vs size

**Comment by IzzySoft** [comment]
As this was closed without a commit or PR linked, and I can find nothing related in the app description: may I ask what for `android.permission.ACCESS_MEDIA_LOCATION` is used/needed?

**Comment by naveensingh** [comment]
@IzzySoft The GPS coordinates are still shown on the 'Properties' dialog, one can click them to view the location in apps that can handle coordinates (e.g. Google Maps).

**Comment by yusufsunetci** [comment]
> @IzzySoft The GPS coordinates are still shown on the 'Properties' dialog, one can click them to view the location in apps that can handle coordinates (e.g. Google Maps).

An open source program called Aves can be reviewed for this. It used Open Street Maps. Very useful.

**Comment by IzzySoft** [comment]
@naveensingh Thanks! Adding that to the "green list" then.

@yusufsunetci Aves is what I use indeed, a real great one by a dev as responsive and great as Naveen :smiley: There are two variants of that one to choose from even. The one at F-Droid only uses "libre map services" (OSM) which I use, the variant in my repo with additional optional map services (e.g. Google Maps) for those preferring them. But then I bet Aves is not as lightweight as Fossify Gallery is :wink: My old FP2 is "sweating" when I try Aves there – on my SHIFT6mq however it runs very fine and smooth.
