### ISSUE TITLE
Swipe Up For Photo Information (Like Apple Photos)

### ISSUE THREAD

**Issue by seniorm0ment** [FossifyOrg/Gallery#84]
**Checklist**
 - [ X] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [ X]  I have read the FAQ and my problem isn't listed.
 - [ X]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [ X]  This issue contains only one feature request.
 - [ X]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
Info menu is a bit lacking and not as pretty as it could be. 

**Describe the solution you'd like**
Personally I really think Apple Photos does a good job. You swipe up on a photo and see all the info.

See: https://support.apple.com/guide/iphone/view-photos-and-videos-iph3d267610/17.0/ios/17.0#iph3d5d1d7dd
For layout example. It shows the phone/device type, iso, shutter, HDR, etc.
Directly below it, it shows a preview of geotag map (#83) which you can click for a full map

**Comment by blackfyre** [comment]
Google Photos does the same, swipe up for more info about the image

**Comment by naveensingh** [comment]
> Info menu is a bit lacking and not as pretty as it could be.

It could be prettier but I think it would be better if you expand on the lacking part. What exactly is missing? We already have the file name, path, size, resolution, last modified, date taken, camera, aperture, focal length, shutter speed, and iso number.

**Comment by seniorm0ment** [comment]
?

**Comment by Aga-C** [comment]
@seniorm0ment There was a question for you: https://github.com/FossifyOrg/Gallery/issues/84#issuecomment-1904826613 which you haven't replied, that's why the issue got closed.

**Comment by camoz** [comment]
I find the swipe up motion also very convenient, and right now it seems unused. Could this issue be reopened, considering the title is "Swipe Up For Photo Information"? Or should I open a new issue for this?

Here's a similar issue from the original "Simple Gallery Pro" repo: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2477

Not sure if it would violate the existing UX of this app too much, but the UI from in the video from the linked issue looks much more ergonomic. Swipe up is completely effortless, compared to reaching to the top-right corner (esp. nowadays where phones are larger). Then, in the tile that swipes up, there are buttons a bit above the vertical middle - exactly where the tip of the thumb normally is when holding the phone with one hand. The EXIF data etc. is displayed below, possibly extending to the bottom of the tile, which is generally hard to reach - perfect for displaying static, non-interactive info!
