### ISSUE TITLE
Fix date cannot work

### ISSUE THREAD

**Issue by llllllllqq** [FossifyOrg/Gallery#88]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
Fix date taken value function cannot work.

**To Reproduce**
1. fresh reinstall.
2. touch a photo to a wrong date than EXIF date.
3. long press it and cick fix date taken value

**Expected behavior**
modified date should be the same as EXIF date.

**Screenshots**

**Device info (please complete the following information):**
 - Model: [Xiaomi redmi K40]
 - OS: [Android 13]
 - App version [1.1.1]

**Additional context**

**Comment by Aga-C** [comment]
After using "Fix date taken" what exactly happens? Does it save any date as "Date taken" in EXIF? If it saves, then which date it saved?

**Comment by llllllllqq** [comment]
> After using "Fix date taken"

nothing happened. The modified date of the photo and EXIF date keep untouched.

**Comment by Aga-C** [comment]
Does file's "Date created" is the same as EXIF "Date taken"?

**Comment by min7-i** [comment]
If I understand the "fix date taken" feature correctly, it won't update the last modified date to match the exif 'date taken' date. In case that is what you expected it to do.

Here's an explanation https://github.com/SimpleMobileTools/Simple-Gallery/issues/2951 that should still be valid:
![grafik](https://github.com/FossifyOrg/Gallery/assets/97251923/97f702bf-517d-4f0e-9b7f-85761bd70ca6)

<details>
<summary>And here's a short video demonstrating the feature.</summary>

The photos are grouped by date taken (monthly), but as you can see the photo is assigned to "Unbekannt" (unknown) although it does have a date taken (exif data). After using the "fix date taken" feature it is correctly assigned to January 2024. Both the modified date and the date taken stay unchanged.

<video src="https://github.com/FossifyOrg/Gallery/assets/97251923/64eb2692-5cfe-4793-860a-92c2e3fc72b8">

</details>

**Comment by Aga-C** [comment]
@min7-i Thanks for the explanation!
