### ISSUE TITLE
Fastlane: short description for gl-ES too long

### ISSUE THREAD

**Issue by IzzySoft** [FossifyOrg/Gallery#91]
Just a short note: Please ensure to stay inside the specifications with text file limitations. Currently your short description for gl-ES counts 83 characters. Everything beyond 80 characters is simply cut off, even mid-word.

**Comment by Aga-C** [comment]
There is already warning about it on Weblate, so translator should be aware of this.

**Comment by IzzySoft** [comment]
I've heard Weblate also allows to "hard-limit" such things (so here, entering a translation exceeding 80 chars would not be possible), but I'm not sure if you want that. I just came here because my own "quality check" (which runs monthly) turned that up for the file in my repo. I can put a "note to self" to not report such things next time if you prefer.

**Comment by naveensingh** [comment]
Okay, I enforced the max length check. It shouldn't happen again.
