### ISSUE TITLE
Strange bug with Primary color

### ISSUE THREAD

**Issue by Artem13327** [FossifyOrg/Gallery#94]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
For some reason, the “Open biometric ID verification dialog” button remains orange when either the default color is selected in "Primary Color" (Also works when the color #3C8F32 is selected, it is before the default color)

**To Reproduce**
1. Go to password protection settings
2. Select fingerprint option
3. See that the button is orange

**Expected behavior**

**Screenshots**

**Device info (please complete the following information):**
 - Model:
 - OS: [e.g. Android 14] Android 11
 - App version [e.g. 6.28.1] 1.1.1

**Additional context**

**Comment by naveensingh** [comment]
It's been fixed in https://github.com/FossifyOrg/Commons/commit/1437ab513f23d93482d0007a5e8811a58f05f037. A new version will be available soon.
