### ISSUE TITLE
[BUG] Instantly see change of favorited images

### ISSUE THREAD

**Issue by inson1** [FossifyOrg/Gallery#99]
Checklist
[X] I can reproduce the bug with the latest version.
[X] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
[X] I have read the FAQ and my problem isn't listed.
[X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
[X] This issue contains only one bug.
[X] I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

Describe the bug
if I click on picture, favorite it and leave back to all all folders content, picture doesnt show favorited (even unfavorite doesnt work)

Expected behavior
Instant change

Device info:
Model: Xiaomi 8 pro
OS: Android 11 
Version: F-Droid 1.1.1

**Comment by Aga-C** [comment]
It sounds like a bug, not a feature request because it works just like you described. Therefore, you should raise it as a new bug report with all details about the device. Especially, that I've just tested it on two different devices and I can't reproduce it.

**Comment by inson1** [comment]
@Aga-C done

**Comment by Aga-C** [comment]
Please just create a new issue, filling out the form properly.
